# Copyright 2025 Maximilian Huber <oss@maximilian-huber.de>
# SPDX-License-Identifier: MIT
{
  config,
  lib,
  pkgs,
  jail,
  ...
}:

let
  osconfig = config;
  callLib = file: import file { inherit lib pkgs; };

  jailLib = jail.init pkgs;

  # Build a provider entry for an OpenAI-compatible base URL.
  mkOpenAiCompatibleProvider =
    {
      key,
      name,
      baseUrl,
      models,
    }:
    {
      inherit key;
      value = {
        inherit name baseUrl;
        api = "openai-completions";
        # Pi requires apiKey when models are provided. Use a literal dummy
        # since the local servers don't validate it.
        apiKey = "DUMMY_API_KEY";
        authHeader = false;
        models = lib.map (modelId: {
          id = modelId;
          name = modelId;
          reasoning = false;
          input = [ "text" ];
          cost = {
            input = 0;
            output = 0;
            cacheRead = 0;
            cacheWrite = 0;
          };
          contextWindow = 128000;
          maxTokens = 4096;
        }) models;
      };
    };

  localModelProviders = lib.map (
    model:
    let
      hostPort = "${model.host}:${toString model.port}";
      providerName = if model.name != null then model.name else hostPort;
      # localModels may contain strings or { name, aliases } submodules.
      modelNames =
        let
          raw = if model.models != [ ] then model.models else [ providerName ];
        in
        lib.map (m: if builtins.isAttrs m then m.name else m) raw;
    in
    mkOpenAiCompatibleProvider {
      key = "local-${providerName}";
      name = hostPort;
      baseUrl = "http://${hostPort}/v1";
      models = modelNames;
    }
  ) osconfig.myconfig.ai.localModels;

  # `host` may be a wildcard (e.g. "0.0.0.0") for external exposure;
  # rewrite to localhost for in-host clients.
  litellmHost =
    if osconfig.services.litellm.host == "0.0.0.0" then "localhost" else osconfig.services.litellm.host;
  litellmProvider = lib.optional osconfig.services.litellm.enable (mkOpenAiCompatibleProvider {
    key = "litellm";
    name = "LiteLLM";
    baseUrl = "http://${litellmHost}:${toString osconfig.services.litellm.port}/v1";
    models = lib.map (m: m.model_name) osconfig.services.litellm.settings.model_list;
  });

  ollamaProvider = lib.optional osconfig.services.ollama.enable (mkOpenAiCompatibleProvider {
    key = "ollama";
    name = "Ollama";
    baseUrl = "http://${osconfig.services.ollama.host}:${toString osconfig.services.ollama.port}/v1";
    models = osconfig.services.ollama.loadModels;
  });

  llamaSwapProvider = lib.optional osconfig.services.llama-swap.enable (mkOpenAiCompatibleProvider {
    key = "llama-swap";
    name = "llama-swap";
    baseUrl = "http://localhost:${toString osconfig.services.llama-swap.port}/v1";
    models = builtins.attrNames osconfig.services.llama-swap.settings.models;
  });

  allProviders = localModelProviders ++ litellmProvider ++ ollamaProvider ++ llamaSwapProvider;

  # Generate a TypeScript extension that registers all providers via
  # pi.registerProvider(). See:
  # https://github.com/badlogic/pi-mono/blob/main/packages/coding-agent/docs/custom-provider.md
  providersExtension =
    let
      providersJson = builtins.toJSON (
        lib.listToAttrs (
          lib.map (p: {
            name = p.key;
            value = p.value;
          }) allProviders
        )
      );
    in
    pkgs.writeText "pi-providers.ts" ''
      // Auto-generated by myconfig.ai.pi-coding-agent. Do not edit by hand.
      import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

      const providers: Record<string, any> = ${providersJson};

      export default function (pi: ExtensionAPI) {
        for (const [key, config] of Object.entries(providers)) {
          pi.registerProvider(key, config);
        }
      }
    '';

  piBwrap = callLib ../fns/sandboxed-app.nix {
    name = "pi";
    pkg = pkgs.nixos-unstable.pi-coding-agent;
    extraRuntimeInputs = [
      pkgs.wget
      pkgs.curl
      pkgs.jq
    ];
    writableDirs = [
      ".pi"
    ];
  };

  # `jailed-pi` is an alternative to `piBwrap` that uses the jail.nix library
  # (vendored at ./vendor/alexdavid-jail.nix) instead of a hand-rolled
  # bubblewrap wrapper. The `jail` argument is provided as a NixOS module
  # specialArg in flake.lib.nix.
  jailed-pi = jailLib "jailed-pi" pkgs.nixos-unstable.pi-coding-agent (
    with jailLib.combinators;
    [
      # Network access for talking to LLM endpoints, including TLS/CA bundle
      # and /etc/resolv.conf etc.
      network

      # Bind the entire `/nix/store` read-only. The base permissions only
      # bind the runtime closure of the jailed derivation; pi shells out to
      # arbitrary tools (git, ripgrep, ...) added via add-pkg-deps and may
      # also exec store paths it discovers in the user's project (e.g.
      # `nix run`, `direnv`, etc.), so we expose the full store instead.
      (ro-bind "/nix/store" "/nix/store")

      # Expose the host's `~/.pi` directory read-write. This is required so
      # the agent picks up the auto-generated provider extension installed by
      # home-manager (`~/.pi/agent/extensions/myconfig-providers.ts`) and so
      # session/credential state persists across invocations.
      (add-runtime "mkdir -p ~/.pi")
      (rw-bind (noescape "~/.pi") (noescape "~/.pi"))

      # Expose the host's `~/tmp` directory read-write inside the jail so
      # pi has a persistent writable scratch space under $HOME.
      (add-runtime "mkdir -p ~/tmp")
      (rw-bind (noescape "~/tmp") (noescape "~/tmp"))

      # Provide a host-backed /tmp instead of the base tmpfs. Creates
      # /tmp/jailed-pi on the host and bind-mounts it as /tmp in the jail,
      # giving pi a real writable /tmp that survives across invocations.
      (add-runtime ''
        mkdir -p /tmp/jailed-pi
        RUNTIME_ARGS+=(--bind /tmp/jailed-pi /tmp)
      '')

      # Bind-mount the working directory read-write so pi can edit files in
      # the user's project. The CWD is the project root (or a worktree, when
      # invoked via `pi-worktree`).
      mount-cwd

      # Expose `/usr/bin` read-only so the agent can inspect host-installed
      # binaries (e.g. `which`, `file`, or system-provided tools outside the
      # Nix store).
      (ro-bind "/usr/bin" "/usr/bin")

      # Expose user config directories read-only so tools inside the jail
      # can pick up host configuration (e.g. ripgrep ignores, bat themes,
      # nix settings, pistol pager config).
      (ro-bind (noescape "~/.config/nix") (noescape "~/.config/nix"))
      (ro-bind (noescape "~/.config/nixpkgs") (noescape "~/.config/nixpkgs"))
      (ro-bind (noescape "~/.config/pistol") (noescape "~/.config/pistol"))
      (ro-bind (noescape "~/.config/ripgrep") (noescape "~/.config/ripgrep"))
      (ro-bind (noescape "~/.config/bat") (noescape "~/.config/bat"))

      # Make common developer tools available inside the jail. pi shells out
      # to git, ripgrep, fd, etc.
      (add-pkg-deps [
        pkgs.git
        pkgs.coreutils
        pkgs.findutils
        pkgs.gnugrep
        pkgs.gnused
        pkgs.gawk
        pkgs.ripgrep
        pkgs.fd
        pkgs.less
        pkgs.which
        pkgs.wget
        pkgs.curl
        pkgs.jq
        pkgs.nix
      ])

      # Forward useful environment variables if they are set on the host.
      (try-fwd-env "TERM")
      (try-fwd-env "COLORTERM")
      (try-fwd-env "LANG")
      (try-fwd-env "LC_ALL")
      (try-fwd-env "EDITOR")
      (try-fwd-env "VISUAL")
    ]
  );
in
{
  options.myconfig = with lib; {
    ai.pi-coding-agent = {
      enable = mkEnableOption "myconfig.ai.pi-coding-agent";
    };
  };
  config = lib.mkIf config.myconfig.ai.pi-coding-agent.enable {
    home-manager.sharedModules = [
      {
        myconfig.persistence.directories = [ ".pi" ];
        home.file.".pi/agent/extensions/myconfig-providers.ts".source = providersExtension;
        home.packages = [
          pkgs.nixos-unstable.pi-coding-agent
          piBwrap
          jailed-pi
          (pkgs.writeShellApplication {
            name = "pi-tmp";
            runtimeInputs = with pkgs; [ coreutils ];
            text = ''
              cd "$(mktemp -d)" && exec ${lib.getExe piBwrap} "$@"
            '';
          })
          (pkgs.writeShellApplication {
            name = "jailed-pi-tmp";
            runtimeInputs = with pkgs; [ coreutils ];
            text = ''
              cd "$(mktemp -d)" && exec ${lib.getExe jailed-pi} "$@"
            '';
          })
          (pkgs.writeShellApplication {
            name = "pi-worktree";
            runtimeInputs = with pkgs; [
              git
              coreutils
            ];
            text = ''
              if [ ! -d .git ]; then
                echo "Error: Not in a git repository root"
                exit 1
              fi

              timestamp=$(date +%s)
              dirname=$(basename "$(pwd)")
              worktree_name="''${dirname}-pi-''${timestamp}"
              branch_name="pi-''${timestamp}"

              git worktree add -b "''${branch_name}" "../''${worktree_name}" || exit 1
              cd "../''${worktree_name}" && exec ${lib.getExe piBwrap} "$@"
            '';
          })
          (pkgs.writeShellApplication {
            name = "jailed-pi-worktree";
            runtimeInputs = with pkgs; [
              git
              coreutils
            ];
            text = ''
              if [ ! -d .git ]; then
                echo "Error: Not in a git repository root"
                exit 1
              fi

              timestamp=$(date +%s)
              dirname=$(basename "$(pwd)")
              worktree_name="''${dirname}-pi-''${timestamp}"
              branch_name="pi-''${timestamp}"

              git worktree add -b "''${branch_name}" "../''${worktree_name}" || exit 1
              cd "../''${worktree_name}" && exec ${lib.getExe jailed-pi} "$@"
            '';
          })
        ];
      }
    ];
  };
}
