# Copyright 2025 Maximilian Huber <oss@maximilian-huber.de>
# SPDX-License-Identifier: MIT
{
  config,
  lib,
  pkgs,
  jail,
  ...
}:

let
  osconfig = config;
  callLib = file: import file { inherit lib pkgs; };
  callJailLib = file: import file { inherit lib pkgs jail; };
  jail-app = callJailLib ../fns/jail-app.nix;

  # Build a provider entry for an OpenAI-compatible base URL.
  mkOpenAiCompatibleProvider =
    {
      key,
      name,
      baseUrl,
      models,
    }:
    {
      inherit key;
      value = {
        inherit name baseUrl;
        api = "openai-completions";
        apiKey = "dummy";
        authHeader = false;
        models = lib.map (modelId: {
          id = modelId;
          name = modelId;
          reasoning = false;
          input = [ "text" ];
          cost = {
            input = 0;
            output = 0;
            cacheRead = 0;
            cacheWrite = 0;
          };
          contextWindow = 128000;
          maxTokens = 4096;
        }) models;
      };
    };

  localModelProviders = lib.map (
    model:
    let
      hostPort = "${model.host}:${toString model.port}";
      providerName = if model.name != null then model.name else hostPort;
      # localModels may contain strings or `{ name, kind ? null }`
      # submodules (computed kind tag is unused here).
      modelNames =
        let
          raw = if model.models != [ ] then model.models else [ providerName ];
        in
        lib.map (m: if builtins.isAttrs m then m.name else m) raw;
    in
    mkOpenAiCompatibleProvider {
      key = "local-${providerName}";
      name = hostPort;
      baseUrl = "http://${hostPort}/v1";
      models = modelNames;
    }
  ) osconfig.myconfig.ai.localModels;

  # `host` may be a wildcard (e.g. "0.0.0.0") for external exposure;
  # rewrite to localhost for in-host clients.
  litellmHost =
    if osconfig.services.litellm.host == "0.0.0.0" then "localhost" else osconfig.services.litellm.host;
  litellmProvider = lib.optional osconfig.services.litellm.enable (mkOpenAiCompatibleProvider {
    key = "litellm";
    name = "LiteLLM";
    baseUrl = "http://${litellmHost}:${toString osconfig.services.litellm.port}/v1";
    models = lib.map (m: m.model_name) osconfig.services.litellm.settings.model_list;
  });

  llamaSwapProvider = lib.optional osconfig.services.llama-swap.enable (mkOpenAiCompatibleProvider {
    key = "llama-swap";
    name = "llama-swap";
    baseUrl = "http://localhost:${toString osconfig.services.llama-swap.port}/v1";
    models = builtins.attrNames osconfig.services.llama-swap.settings.models;
  });

  allProviders = localModelProviders ++ litellmProvider ++ llamaSwapProvider;

  # Generate a TypeScript extension that registers all providers via
  # pi.registerProvider(). See:
  # https://github.com/badlogic/pi-mono/blob/main/packages/coding-agent/docs/custom-provider.md
  providersExtension =
    let
      providersJson = builtins.toJSON (
        lib.listToAttrs (
          lib.map (p: {
            name = p.key;
            value = p.value;
          }) allProviders
        )
      );
    in
    pkgs.writeText "pi-providers.ts" ''
      // Auto-generated by myconfig.ai.pi-coding-agent. Do not edit by hand.
      import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

      const providers: Record<string, any> = ${providersJson};

      export default function (pi: ExtensionAPI) {
        for (const [key, config] of Object.entries(providers)) {
          pi.registerProvider(key, config);
        }
      }
    '';

  # Extension that shows whether the current pi session is sandboxed. Both
  # `pi`/`piBwrap` and `jailed-pi` wrap the same `pi-coding-agent` binary and
  # share the same `~/.pi/settings.json` (hence the same theme), so the two
  # are otherwise indistinguishable in the TUI. `jailed-pi` sets
  # `PI_JAIL_MARKER=1` inside the jail (see `extraRuntimeEnv` below); this
  # extension reads it and, when set, switches to the built-in `dark` theme so
  # jailed sessions are visually distinct. Plain `pi` keeps whatever theme is
  # configured in `settings.json` (currently `light`). The default footer
  # (git stats, model, etc.) is left untouched in both cases.
  jailMarkerExtension = pkgs.writeText "pi-jail-marker.ts" ''
    // Auto-generated by myconfig.ai.pi-coding-agent. Do not edit by hand.
    // Switches to the `dark` theme when pi runs inside the `jailed-pi`
    // sandbox (PI_JAIL_MARKER=1), leaving the default footer intact. In the
    // plain `pi` wrapper the variable is unset and this is a no-op.
    import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

    const JAILED_THEME = "dark";

    export default function (pi: ExtensionAPI) {
      if (process.env.PI_JAIL_MARKER !== "1") return;

      pi.on("session_start", async (_event: any, ctx: any) => {
        const result = ctx.ui.setTheme(JAILED_THEME);
        if (result && result.success === false) {
          ctx.ui.notify(
            `jail-marker: failed to set theme ''${JAILED_THEME}: ''${result.error}`,
            "error",
          );
        }
      });
    }
  '';

  piBwrap = callLib ../fns/sandboxed-app.nix {
    name = "pi";
    pkg = pkgs.nixos-unstable.pi-coding-agent;
    extraRuntimeInputs = [
      pkgs.wget
      pkgs.curl
      pkgs.jq
    ];
    writableDirs = [
      ".pi"
    ];
    # Read-only bind of `~/.agents/skills/`, where `myconfig.ai.skills`
    # deploys handcrafted skills for pi (which has no `programs.pi.skills`
    # option). See `modules/myconfig.ai/skills/default.nix`.
    readOnlyConfigDirs = [ ".agents" ];
  };

  # `jailed-pi` is an alternative to `piBwrap` that uses the jail.nix library
  # (vendored at ./vendor/alexdavid-jail.nix) instead of a hand-rolled
  # bubblewrap wrapper. See `../fns/jail-app.nix` for the shared defaults.
  #
  # `~/.pi` is rw-bound because the agent picks up the auto-generated
  # provider extension installed by home-manager
  # (`~/.pi/agent/extensions/myconfig-providers.ts`) and so session and
  # credential state persists across invocations.
  jailed-pi = jail-app {
    name = "jailed-pi";
    pkg = pkgs.nixos-unstable.pi-coding-agent;
    userDataDirs = [ ".pi" ];
    # Read-only bind of `~/.agents/skills/` so pi discovers the handcrafted
    # skills deployed there by `myconfig.ai.skills`. Bound via
    # `extraConfigDirs` (try-ro-bind inside `jail-app.nix`), so the jail still
    # starts on a host where `.agents` has not been deployed.
    extraConfigDirs = [ ".agents" ];
    # Marker so `jailed-pi` sessions are visually distinguishable from the
    # plain `pi`/`piBwrap` wrapper (which share the same `~/.pi/settings.json`,
    # hence the same theme). The `myconfig-jail-marker.ts` extension (deployed
    # below) reads this variable and switches to the `dark` theme when it is
    # set, leaving the default footer intact.
    extraRuntimeEnv.PI_JAIL_MARKER = "1";
  };
in
{
  options.myconfig = with lib; {
    ai.pi-coding-agent = {
      enable = mkEnableOption "myconfig.ai.pi-coding-agent";
    };
  };
  config = lib.mkIf config.myconfig.ai.pi-coding-agent.enable {
    home-manager.sharedModules = [
      {
        myconfig.persistence.directories = [ ".pi" ];
        home.file.".pi/agent/extensions/myconfig-providers.ts".source = providersExtension;
        home.file.".pi/agent/extensions/myconfig-jail-marker.ts".source = jailMarkerExtension;
        home.packages = [
          pkgs.nixos-unstable.pi-coding-agent
          piBwrap
          jailed-pi
          (pkgs.writeShellApplication {
            name = "pi-tmp";
            runtimeInputs = with pkgs; [ coreutils ];
            text = ''
              cd "$(mktemp -d)" && exec ${lib.getExe piBwrap} "$@"
            '';
          })
          (pkgs.writeShellApplication {
            name = "jailed-pi-tmp";
            runtimeInputs = with pkgs; [ coreutils ];
            text = ''
              cd "$(mktemp -d)" && exec ${lib.getExe jailed-pi} "$@"
            '';
          })
          (pkgs.writeShellApplication {
            name = "pi-worktree";
            runtimeInputs = with pkgs; [
              git
              coreutils
            ];
            text = ''
              if [ ! -d .git ]; then
                echo "Error: Not in a git repository root"
                exit 1
              fi

              timestamp=$(date +%s)
              dirname=$(basename "$(pwd)")
              worktree_name="''${dirname}-pi-''${timestamp}"
              branch_name="pi-''${timestamp}"

              git worktree add -b "''${branch_name}" "../''${worktree_name}" || exit 1
              cd "../''${worktree_name}" && exec ${lib.getExe piBwrap} "$@"
            '';
          })
          (pkgs.writeShellApplication {
            name = "jailed-pi-worktree";
            runtimeInputs = with pkgs; [
              git
              coreutils
            ];
            text = ''
              if [ ! -d .git ]; then
                echo "Error: Not in a git repository root"
                exit 1
              fi

              timestamp=$(date +%s)
              dirname=$(basename "$(pwd)")
              worktree_name="''${dirname}-pi-''${timestamp}"
              branch_name="pi-''${timestamp}"

              git worktree add -b "''${branch_name}" "../''${worktree_name}" || exit 1
              cd "../''${worktree_name}" && exec ${lib.getExe jailed-pi} "$@"
            '';
          })
        ];
      }
    ];
  };
}
