# Test for transform function and packages options
{ pkgs, agentLib }:

let
  testSources = {
    test-fixtures = {
      path = ./fixtures/test-skill;
    };
  };

  testCatalog = agentLib.discoverCatalog testSources;

  # Case 1: No packages, no transform (original only)
  testSelectionOriginalOnly = agentLib.selectSkills {
    catalog = testCatalog;
    allowlist = [];
    sources = testSources;
    skills = {
      test-skill-original-only = {
        from = "test-fixtures";
        path = ".";
      };
    };
  };

  # Case 2: Packages only, no transform (dependencies + original)
  testSelectionPackagesOnly = agentLib.selectSkills {
    catalog = testCatalog;
    allowlist = [];
    sources = testSources;
    skills = {
      test-skill-packages-only = {
        from = "test-fixtures";
        path = ".";
        packages = [ pkgs.jq ];
      };
    };
  };

  # Case 3: Packages + transform (full customisation with dependencies)
  testSelectionPackagesTransform = agentLib.selectSkills {
    catalog = testCatalog;
    allowlist = [];
    sources = testSources;
    skills = {
      test-skill-packages-transform = {
        from = "test-fixtures";
        path = ".";
        packages = [ pkgs.bun ];
        transform = { original, dependencies }: ''
# Custom Header

${dependencies}
---

${original}

---
# Custom Footer
Generated by transform function.
'';
      };
    };
  };

  # Case 4: Transform only, no packages
  testSelectionTransformOnly = agentLib.selectSkills {
    catalog = testCatalog;
    allowlist = [];
    sources = testSources;
    skills = {
      test-skill-transform-only = {
        from = "test-fixtures";
        path = ".";
        transform = { original, dependencies }: ''
# Wrapped Skill

${original}

# End of Skill
'';
      };
    };
  };

  # Rewrite test sources
  rewriteSources = {
    rewrite-fixtures = {
      path = ./fixtures/rewrite-skill;
    };
  };

  rewriteCatalog = agentLib.discoverCatalog rewriteSources;

  # Case 6: rewriteCommands = true (default) with packages
  testSelectionRewrite = agentLib.selectSkills {
    catalog = rewriteCatalog;
    allowlist = [];
    sources = rewriteSources;
    skills = {
      test-skill-rewrite = {
        from = "rewrite-fixtures";
        path = ".";
        packages = [ pkgs.jq ];
      };
    };
  };

  # Case 7: rewriteCommands = false with packages
  testSelectionRewriteDisabled = agentLib.selectSkills {
    catalog = rewriteCatalog;
    allowlist = [];
    sources = rewriteSources;
    skills = {
      test-skill-rewrite-disabled = {
        from = "rewrite-fixtures";
        path = ".";
        packages = [ pkgs.jq ];
        rewriteCommands = false;
      };
    };
  };

  # Case 8: multi-binary packages are not rewritten to missing ./binary paths
  testSelectionRewriteMultiBin = agentLib.selectSkills {
    catalog = rewriteCatalog;
    allowlist = [];
    sources = rewriteSources;
    skills = {
      test-skill-rewrite-multi-bin = {
        from = "rewrite-fixtures";
        path = ".";
        packages = [ pkgs.bun ];
      };
    };
  };

  # Case 5: Error case - transform is not a function
  invalidSelection = agentLib.selectSkills {
    catalog = testCatalog;
    allowlist = [];
    sources = testSources;
    skills = {
      test-skill-invalid = {
        from = "test-fixtures";
        path = ".";
        transform = "not a function";  # Should cause error
      };
    };
  };
  # Force deep evaluation to trigger the error
  testInvalidTransform = builtins.tryEval (builtins.deepSeq invalidSelection invalidSelection);

  testBundleOriginalOnly = agentLib.mkBundle {
    inherit pkgs;
    selection = testSelectionOriginalOnly;
    name = "agent-skills-test-original-only";
  };

  testBundlePackagesOnly = agentLib.mkBundle {
    inherit pkgs;
    selection = testSelectionPackagesOnly;
    name = "agent-skills-test-packages-only";
  };

  testBundlePackagesTransform = agentLib.mkBundle {
    inherit pkgs;
    selection = testSelectionPackagesTransform;
    name = "agent-skills-test-packages-transform";
  };

  testBundleTransformOnly = agentLib.mkBundle {
    inherit pkgs;
    selection = testSelectionTransformOnly;
    name = "agent-skills-test-transform-only";
  };

  testBundleRewrite = agentLib.mkBundle {
    inherit pkgs;
    selection = testSelectionRewrite;
    name = "agent-skills-test-rewrite";
  };

  testBundleRewriteDisabled = agentLib.mkBundle {
    inherit pkgs;
    selection = testSelectionRewriteDisabled;
    name = "agent-skills-test-rewrite-disabled";
  };

  testBundleRewriteMultiBin = agentLib.mkBundle {
    inherit pkgs;
    selection = testSelectionRewriteMultiBin;
    name = "agent-skills-test-rewrite-multi-bin";
  };
in
pkgs.runCommand "agent-skills-transform-packages-test" {} ''
  set -e

  echo "=== Case 1: Original only (no packages, no transform) ==="
  skillDir1="${testBundleOriginalOnly}/test-skill-original-only"

  # Should be a symlink to original directory
  test -L "$skillDir1" || { echo "Should be a symlink for original-only case"; exit 1; }

  # Check original content
  grep -q "# Test Skill" "$skillDir1/SKILL.md" || { echo "Original content not found"; exit 1; }

  # Should NOT have Dependencies section
  ! grep -q "## Dependencies" "$skillDir1/SKILL.md" || { echo "Should not have Dependencies section"; exit 1; }

  echo "Case 1 passed!"

  echo ""
  echo "=== Case 2: Packages only (no transform) ==="
  skillMd2="${testBundlePackagesOnly}/test-skill-packages-only/SKILL.md"
  skillDir2="${testBundlePackagesOnly}/test-skill-packages-only"

  # Check file exists
  test -f "$skillMd2" || { echo "SKILL.md not found"; exit 1; }

  # Check Dependencies table exists with local paths
  grep -q "## Dependencies" "$skillMd2" || { echo "Dependencies section not found"; exit 1; }
  grep -q "| jq | \`./jq\` |" "$skillMd2" || { echo "jq package not found with local path"; exit 1; }

  # Check symlink to package binary exists and works
  test -L "$skillDir2/jq" || { echo "jq symlink not found"; exit 1; }
  "$skillDir2/jq" --version > /dev/null || { echo "jq is not executable"; exit 1; }

  # Check original content is included
  grep -q "# Test Skill" "$skillMd2" || { echo "Original content not found"; exit 1; }

  # Check order: Original -> Dependencies (preserves frontmatter)
  deps_line=$(grep -n "## Dependencies" "$skillMd2" | head -1 | cut -d: -f1)
  original_line=$(grep -n "# Test Skill" "$skillMd2" | head -1 | cut -d: -f1)
  test "$original_line" -lt "$deps_line" || { echo "Original should come before Dependencies"; exit 1; }

  echo "Case 2 passed!"

  echo ""
  echo "=== Case 3: Packages + transform ==="
  skillMd3="${testBundlePackagesTransform}/test-skill-packages-transform/SKILL.md"
  skillDir3="${testBundlePackagesTransform}/test-skill-packages-transform"

  # Check file exists
  test -f "$skillMd3" || { echo "SKILL.md not found"; exit 1; }

  # Check custom header from transform
  grep -q "# Custom Header" "$skillMd3" || { echo "Custom header not found"; exit 1; }

  # Check custom footer from transform
  grep -q "# Custom Footer" "$skillMd3" || { echo "Custom footer not found"; exit 1; }

  # Check original content is included
  grep -q "# Test Skill" "$skillMd3" || { echo "Original content not found"; exit 1; }

  # Check Dependencies table (bun has multiple binaries)
  grep -q "| bun |" "$skillMd3" || { echo "bun package not found in table"; exit 1; }
  grep -q "(contains:" "$skillMd3" || { echo "Multiple binaries note not found"; exit 1; }

  # Check bun directory symlink works
  test -L "$skillDir3/bun" || { echo "bun symlink not found"; exit 1; }
  test -x "$skillDir3/bun/bun" || { echo "bun binary not found"; exit 1; }
  test -x "$skillDir3/bun/bunx" || { echo "bunx binary not found"; exit 1; }

  echo "Case 3 passed!"

  echo ""
  echo "=== Case 4: Transform only (no packages) ==="
  skillMd4="${testBundleTransformOnly}/test-skill-transform-only/SKILL.md"
  skillDir4="${testBundleTransformOnly}/test-skill-transform-only"

  # Check file exists
  test -f "$skillMd4" || { echo "SKILL.md not found"; exit 1; }

  # Check custom wrapper from transform
  grep -q "# Wrapped Skill" "$skillMd4" || { echo "Wrapper header not found"; exit 1; }
  grep -q "# End of Skill" "$skillMd4" || { echo "Wrapper footer not found"; exit 1; }

  # Check original content is included
  grep -q "# Test Skill" "$skillMd4" || { echo "Original content not found"; exit 1; }

  # Should NOT have Dependencies section (no packages)
  ! grep -q "## Dependencies" "$skillMd4" || { echo "Should not have Dependencies section"; exit 1; }

  echo "Case 4 passed!"

  echo ""
  echo "=== Case 5: Error case (invalid transform) ==="
  # testInvalidTransform.success should be false because transform is not a function
  ${if testInvalidTransform.success then ''
    echo "ERROR: Invalid transform should have failed but succeeded"
    exit 1
  '' else ''
    echo "Correctly rejected non-function transform"
  ''}

  echo "Case 5 passed!"

  echo ""
  echo "=== Case 6: rewriteCommands = true (default) ==="
  skillMd6="${testBundleRewrite}/test-skill-rewrite/SKILL.md"

  test -f "$skillMd6" || { echo "SKILL.md not found"; exit 1; }

  # Bare "jq " should be rewritten to "./jq "
  grep -q '\./jq ' "$skillMd6" || { echo "jq not rewritten to ./jq"; exit 1; }

  # "| jq " should become "| ./jq "
  grep -q '| \./jq ' "$skillMd6" || { echo "piped jq not rewritten"; exit 1; }

  # Already-prefixed "./jq" should NOT become "././jq"
  ! grep -q '\./\./jq' "$skillMd6" || { echo "Double-prefixed ././jq found"; exit 1; }

  # Original bare "jq " at start of line should not remain
  ! grep -q '^jq ' "$skillMd6" || { echo "Bare jq still present at start of line"; exit 1; }

  echo "Case 6 passed!"

  echo ""
  echo "=== Case 7: rewriteCommands = false ==="
  skillMd7="${testBundleRewriteDisabled}/test-skill-rewrite-disabled/SKILL.md"

  test -f "$skillMd7" || { echo "SKILL.md not found"; exit 1; }

  # Bare "jq " should remain (not rewritten)
  grep -q '^jq ' "$skillMd7" || { echo "Bare jq should remain when rewriteCommands=false"; exit 1; }

  # Dependencies table should still be present
  grep -q "## Dependencies" "$skillMd7" || { echo "Dependencies section not found"; exit 1; }

  echo "Case 7 passed!"

  echo ""
  echo "=== Case 8: rewriteCommands skips multi-binary packages ==="
  skillMd8="${testBundleRewriteMultiBin}/test-skill-rewrite-multi-bin/SKILL.md"
  skillDir8="${testBundleRewriteMultiBin}/test-skill-rewrite-multi-bin"

  test -f "$skillMd8" || { echo "SKILL.md not found"; exit 1; }

  # bun exposes multiple binaries under ./bun/, so bare bunx must not become a missing ./bunx path.
  grep -q '^bunx --version' "$skillMd8" || { echo "Bare bunx should remain for multi-binary package"; exit 1; }
  ! grep -q '\./bunx' "$skillMd8" || { echo "bunx was rewritten to missing ./bunx path"; exit 1; }

  # The actual multi-binary package layout should still be available.
  test -L "$skillDir8/bun" || { echo "bun symlink not found"; exit 1; }
  test -x "$skillDir8/bun/bun" || { echo "bun binary not found"; exit 1; }
  test -x "$skillDir8/bun/bunx" || { echo "bunx binary not found"; exit 1; }

  echo "Case 8 passed!"

  echo ""
  echo "All tests passed!"
  mkdir -p "$out"
  touch "$out/ok"
''
