# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/gorilla/websocket";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/websocket";
      rev = "c3dd95aea9779669bb3daafbd84ee0530c8ce1c1";
      sha256 = "0ny2r232jivr1d611gavz5ws3y3r8b5cd2als9544lr0v0m5cikw";
    };
  }
  {
    goPackagePath = "github.com/influxdata/influxdb1-client";
    fetch = {
      type = "git";
      url = "https://github.com/influxdata/influxdb1-client";
      rev = "b269163b24ab8e62026d13a92aa988a7389c3b4e";
      sha256 = "0pm1j437xk7d32px60j52qm98zgn21nmaqavjflvr44zaglrz5n9";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "7649d4548cb53a614db133b2a8ac1f31859dda8c";
      sha256 = "1pbmrpj7gcws34g8vwna4i2nhm9p6235piww36436xhyaa10cldr";
    };
  }
]
