[
  ./myconfig
  ./myemacs
  ./myvim
  ./myxmonad
  # modules
  ./core.nix
  ./crypt.nix
  ./dev
  ./exfat.nix
  ./gnupg.nix
  ./hardware.bluetooth
  ./make-linux-fast-again.nix
  ./mybackup.nix
  ./myconfig.service.deconz.nix
  ./nixos.gc.nix
  ./nixos.networking
  ./nixos.nix.nix
  ./nixos.nix-index.nix
  ./nixos.user.nix
  ./programs.pass
  ./programs.taskwarrior.nix
  ./services.netdata.nix
  ./services.openssh.nix
  ./services.postgresql.nix
  ./services.syncthing.nix
  ./services.vsftp.nix
  ./services.xserver.autorandr.nix
  ./services.xserver.big-cursor.nix
  ./services.xserver.fonts.nix
  ./services.xserver.kernel.nix
  ./services.xserver.mkscreenshot.nix
  ./services.xserver.nix
  ./services.xserver.printing.nix
  ./services.xserver.programs.appimage-run.nix
  ./services.xserver.programs.chromium.nix
  ./services.xserver.programs.deskreen.nix
  ./services.xserver.programs.evolution.nix
  ./services.xserver.programs.firefox.nix
  ./services.xserver.programs.kitty.nix
  ./services.xserver.programs.obs.nix
  ./services.xserver.programs.qutebrowser.nix
  ./services.xserver.programs.vscode.nix
  ./services.xserver.programs.xss-lock.nix
  ./services.xserver.programs.zathura.nix
  ./services.xserver.audio.nix
  ./services.xserver.st
  ./services.xserver.wacom.nix
  ./services.xserver.xclip.nix
  ./shell.common
  ./shell.programs.dic.nix
  ./shell.git
  ./shell.programs.bat.nix
  ./shell.programs.exa.nix
  ./shell.programs.htop.nix
  ./shell.programs.lf.nix
  ./shell.programs.nnn.nix
  ./shell.programs.tmux
  ./shell.zsh
  ./spellchecking.nix
  ./virtualization.oci-containers
  ./virtualization.libvirt.nix
  ./virtualization.lxc.nix
  ./virtualization.qemu.nix
  ./virtualization.vbox.nix
  ./desktop.Wayland.dwl
  ./desktop.Wayland.river
  ./desktop.Wayland.sway
  ./desktop.Wayland.qtile
]
