#!/bin/bash

# Variables
FOLDER="/home/hubi/myconfig/UDOO/"

udooFiles() {
  cat <<UDOOFILES
~/.config/beets/config.yaml
/etc/mpd.conf
/etc/dnsmasq.conf
/etc/sysctl.d/90-inotify.conf
UDOOFILES
}

#RUN
echo "copy"
echo

[[ "$(hostname)" == "udoo" ]] && {
  echo "copy"
  echo
  udooFiles | while IFS= read -r FILE; do
    [[ ! $FILE == \#* ]] && {
      BASE=${FILE##*/}
      BASE=${BASE#.}
      [[ $BASE == *"*"* ]] && BASE=""
      DIR=""
      [[ $FILE == ~* ]] && {
        FILE=${FILE#\~}
        DIR=${FILE%/*}
        [[ $DIR != "" ]] && {
          DIR=${DIR#*/}"/"
          DIR=${DIR#.}
        }
        FILE="/home/hubi"${FILE}
      } || {
        DIR=${FILE%/*}
        DIR=${DIR#*/}"/"
        DIR=${DIR#.}
      }

      mkdir -p "${FOLDER}${DIR}"
      cp -vu $FILE "${FOLDER}${DIR}${BASE}"
      git add "${FOLDER}${DIR}${BASE}"

      if [ -f "$FILE"  ]; then
        cmp -s $FILE "${FOLDER}${DIR}${BASE}" > /dev/null
        if [ $? -eq 1 ]; then
          echo "${FILE} is different"
        fi
      fi
    }
  done
}

echo
echo "git"
echo

cd "$FOLDER"
git add .
git commit -a -m "aktualisiert"
git push
