#!/bin/bash

# Variables
FOLDER="/home/hubi/myconfig/UDOO/"

#RUN
echo "copy"
echo

while IFS= read -r FILE; do
  [[ ! $FILE == \#* ]] && {
    BASE=${FILE##*/}
    BASE=${BASE#.}
    [[ $BASE == *"*"* ]] && BASE=""
    DIR=""
    [[ $FILE == ~* ]] && {
      FILE=${FILE#\~}
      DIR=${FILE%/*}
      [[ $DIR != "" ]] && {
        DIR=${DIR#*/}"/"
        DIR=${DIR#.}
      }
      FILE="/home/hubi"${FILE}
    } || {
      DIR=${FILE%/*}
      DIR=${DIR#*/}"/"
      DIR=${DIR#.}
    }
    mkdir -p "${FOLDER}${DIR}"
    cp -vu $FILE "${FOLDER}${DIR}${BASE}"

  }
done <<FILES
~/.config/beets/config.yaml
/etc/mpd.conf
/etc/dnsmasq.conf
/etc/sysctl.d/90-inotify.conf
FILES

echo
echo "git"
echo

cd "$FOLDER"
git add .
git commit -a -m "aktualisiert"
git push
