# ~/.bash_profile
#
# written by maximilian-huber.de
#
# Last modified: Thu May 22, 2014  05:31

[[ -f ~/.zshrc ]] && . ~/.zshrc

# my login manager
if [[ -z "$DISPLAY" ]] && [[ $(tty) = /dev/tty1 ]]; then
    run_under_tmux 'ncmpcpp'
    ncmpcpp
fi
