#!/bin/bash

FOLDER="/home/hubi/myconfig/"

echo "copy"
echo

while IFS= read -r FILE; do
  [[ ! $FILE == \#* ]] && {
    BASE=${FILE##*/}
    BASE=${BASE#.}
    [[ $BASE == *"*"* ]] && BASE=""
    DIR=""
    [[ $FILE == ~* ]] && {
      FILE=${FILE#\~}
      DIR=${FILE%/*}
      [[ $DIR != "" ]] && {
        DIR=${DIR#*/}"/"
        DIR=${DIR#.}
      }
      FILE="/home/hubi"${FILE}
    } || {
      DIR=${FILE%/*}
      DIR=${DIR#*/}"/"
      DIR=${DIR#.}
    }
    mkdir -p "${FOLDER}${DIR}"
    cp -vu $FILE "${FOLDER}${DIR}${BASE}"
  }
done <<EOF
~/.aliasrc
~/.asoundrc.default
~/.asoundrc.hdmi-connected
~/.asoundrc.uca202
~/.bash_profile
~/.bashrc
~/.emacs
~/.fontconfig/fonts.conf
~/.tmux.conf
~/.vimencrypt
~/.vimrc
~/.vimrc-neo
~/.xinitrc
~/.xmonad/myinformation.sh
~/.xmonad/showkeys
~/.xmonad/xmobarrc
~/.xmonad/xmonad.hs
~/.Xresources
~/.zshrc.local
~/bin/disp-controll
~/bin/installiere_neo
~/bin/mailclient.sh
~/bin/mailrun.sh
~/bin/myautosetup.sh
~/bin/mycrypt
~/bin/myfsize.sh
~/bin/myfullbackup.sh
~/bin/mylayouttoggle.sh
~/bin/nmgui
~/bin/remove_spaces.sh
~/bin/runNL.sh
/etc/X11/xorg.conf.d/*.conf
/etc/hosts
/etc/locale.conf
/etc/mkinitcpio.conf
/etc/modprobe.d/*
/etc/pacman.conf
/etc/vconsole.conf
/usr/share/kbd/keymaps/neo/*
EOF

echo
echo "git"
echo

cd "$FOLDER"
git add .
git commit -a -m "aktualisiert"
git push
