#!/bin/bash

# !!!
# Not working yet!
# !!!

FOLDER="/home/hubi/myconfig/"

while IFS= read -r LINE; do
  echo ${LINE##* }

  # TODO:
  #     * Abfrage geht noch nicht!
  #     * Sudo, wenn nötig

  read -p "${LINE##* }? " -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
      exit 1
  fi
done <<COMMANDS
${FOLDER}Xresources /home/hubi/.Xresources
${FOLDER}aliasrc /home/hubi/.aliasrc
${FOLDER}asoundrc.default /home/hubi/.asoundrc.default
${FOLDER}asoundrc.hdmi-connected /home/hubi/.asoundrc.hdmi-connected
${FOLDER}asoundrc.uca202 /home/hubi/.asoundrc.uca202
${FOLDER}bash_profile /home/hubi/.bash_profile
${FOLDER}bashrc /home/hubi/.bashrc
${FOLDER}config/ranger/rc.conf /home/hubi/.config/ranger/rc.conf
${FOLDER}config/ranger/rifle.conf /home/hubi/.config/ranger/rifle.conf
${FOLDER}emacs /home/hubi/.emacs
${FOLDER}fontconfig/fonts.conf /home/hubi/.fontconfig/fonts.conf
${FOLDER}ghci /home/hubi/.ghci
${FOLDER}gitconfig /home/hubi/.gitconfig
${FOLDER}mutt/colors.solarized-light /home/hubi/.mutt/colors.solarized-light
${FOLDER}ncmpcpp/config /home/hubi/.ncmpcpp/config
${FOLDER}tmux.conf /home/hubi/.tmux.conf
${FOLDER}vimencrypt /home/hubi/.vimencrypt
${FOLDER}vimrc /home/hubi/.vimrc
${FOLDER}vimrc-neo /home/hubi/.vimrc-neo
${FOLDER}xinitrc /home/hubi/.xinitrc
${FOLDER}xmonad/myinformation.sh /home/hubi/.xmonad/myinformation.sh
${FOLDER}xmonad/showkeys /home/hubi/.xmonad/showkeys
${FOLDER}xmonad/xmobarrc /home/hubi/.xmonad/xmobarrc
${FOLDER}xmonad/xmonad.hs /home/hubi/.xmonad/xmonad.hs
${FOLDER}zshrc.local /home/hubi/.zshrc.local
${FOLDER}bin/disp-controll /home/hubi/bin/disp-controll
${FOLDER}bin/installiere_neo /home/hubi/bin/installiere_neo
${FOLDER}bin/mailclient.sh /home/hubi/bin/mailclient.sh
${FOLDER}bin/mailrun.sh /home/hubi/bin/mailrun.sh
${FOLDER}bin/myautosetup.sh /home/hubi/bin/myautosetup.sh
${FOLDER}bin/mycrypt /home/hubi/bin/mycrypt
${FOLDER}bin/myfsize.sh /home/hubi/bin/myfsize.sh
${FOLDER}bin/myfullbackup.sh /home/hubi/bin/myfullbackup.sh
${FOLDER}bin/mylayouttoggle.sh /home/hubi/bin/mylayouttoggle.sh
${FOLDER}bin/ncChat.sh /home/hubi/bin/ncChat.sh
${FOLDER}bin/nmgui /home/hubi/bin/nmgui
${FOLDER}bin/remove_spaces.sh /home/hubi/bin/remove_spaces.sh
${FOLDER}bin/runNL.sh /home/hubi/bin/runNL.sh
${FOLDER}etc/X11/xorg.conf.d/ /etc/X11/xorg.conf.d/*.conf
${FOLDER}etc/hosts /etc/hosts
${FOLDER}etc/locale.conf /etc/locale.conf
${FOLDER}etc/mkinitcpio.conf /etc/mkinitcpio.conf
${FOLDER}etc/modprobe.d/ /etc/modprobe.d/*
${FOLDER}etc/pacman.conf /etc/pacman.conf
${FOLDER}etc/vconsole.conf /etc/vconsole.conf
${FOLDER}etc/vsftpd.conf /etc/vsftpd.conf
${FOLDER}etc/zathurarc /etc/zathurarc
${FOLDER}usr/share/kbd/keymaps/neo/ /usr/share/kbd/keymaps/neo/*
COMMANDS
