#!/bin/bash

# !!!
# Not working yet!
# !!!

FOLDER="/home/hubi/myconfig/"

while IFS= read -r LINE; do
  echo ${LINE##* }

  # TODO:
  #     * Abfrage geht noch nicht!
  #     * Sudo, wenn nötig

  read -p "${LINE##* }? " -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
      exit 1
  fi
done <<COMMANDS
${FOLDER}etc/fstab /etc/fstab
${FOLDER}etc/hosts /etc/hosts
${FOLDER}etc/locale.conf /etc/locale.conf
${FOLDER}etc/lvm/lvm.conf /etc/lvm/lvm.conf
${FOLDER}etc/mkinitcpio.conf /etc/mkinitcpio.conf
${FOLDER}etc/pacman.conf /etc/pacman.conf
${FOLDER}etc/sysctl.d/99-sysctl.conf /etc/sysctl.d/99-sysctl.conf
${FOLDER}etc/vconsole.conf /etc/vconsole.conf
${FOLDER}etc/vsftpd.conf /etc/vsftpd.conf
${FOLDER}etc/zathurarc /etc/zathurarc
COMMANDS
