#!/bin/bash

# !!!
# Not working yet!
# !!!

FOLDER="/home/hubi/myconfig/"

while IFS= read -r LINE; do
  echo ${LINE##* }

  # TODO:
  #     * Abfrage geht noch nicht!
  #     * Sudo, wenn nötig

  read -p "${LINE##* }? " -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
      exit 1
  fi
done <<COMMANDS
COMMANDS
