# Copyright 2026 Maximilian Huber <oss@maximilian-huber.de>
# SPDX-License-Identifier: MIT
#
# `mysbx-herdr-entry` — the INTERACTIVE payload of a
# `multiplexer = "herdr"` mysbx sandbox (../docs/design/config.md D17,
# ../docs/design/cli.md D11).
#
# herdr (https://herdr.dev) is an "agent multiplexer that lives in your
# terminal"; the host installation and the bubblewrap-jail tier of it
# live in ../../programs/programs.herdr.nix. This is the mysbx tier, expressed as
# configuration instead of a wrapper binary: `cd <repo> && mysbx` with
# `multiplexer = "herdr"` in a layer.
#
# Differences from the other entries, all consequences of herdr not
# being a tmux server:
#
#   * herdr's socket, server state and session config live under the
#     sandbox `HOME` (`/mysbx-home`, a tmpfs, ../docs/design/config.md
#     D14) — `~/.config/herdr/herdr.sock` and friends — so they are
#     per-sandbox and per-run by construction: the D16/D17 socket
#     isolation holds without herdr having to be told anything. (Older
#     herdr versions had a `--no-session` "monolithic" mode for this;
#     current ones removed it, and the tmpfs `HOME` makes it
#     unnecessary.)
#   * `TMUX_TMPDIR` is still exported by mysbx and still validated here:
#     it is how a pane that runs plain `tmux` inside the herdr session
#     lands on the private socket instead of `/tmp/tmux-<uid>`.
#
# Worktree placement follows the workmux convention
# (`../../programs/programs.herdr.README.md`): herdr's `[worktrees]
# directory` is a single global root with no per-repo placeholders, but
# a mysbx sandbox has exactly ONE repository, so the option is made
# repository-local at start time — the same trick the bubblewrap-jail
# tier (`herdr-jail-entry`) uses. The root points at the
# `<repo>__worktrees` sibling, which the argv builder binds rw at its
# real host path when it EXISTS (`repo.rs::Repo::worktrees`): the `-d`
# test below is therefore the bind test, and mysbx's guard ("a run
# never creates the sibling") is preserved — the script only ever
# CONFIGURES an existing, bound directory. Without the sibling the key
# stays unset and herdr falls back to its own default, which lives in
# the tmpfs `HOME` and is therefore ephemeral — the honest outcome for
# a path no layer declared. herdr still appends
# `<repo-name>/<branch-slug>` to its root, so checkouts land one level
# deeper than workmux puts them, inside the same sibling.
#
# The session configuration is written into the tmpfs `HOME` on every
# start, so it can never be stale, and the host's `~/.config/herdr` is
# deliberately not bound. `onboarding = false` is what keeps herdr from
# showing its first-run wizard in every sandbox (the tmpfs home makes
# every start a first run) — the same reason ../../programs/programs.herdr.nix
# gives for its jail config.
{
  lib,
  writeShellApplication,
  coreutils,
  bashInteractive,
  tmux,
  # `jq` reads the workspace ids out of the socket API's JSON answers
  # when the startup workspace is relocated below.
  jq,
  # The herdr package that runs inside the sandbox
  # (`myconfig.ai.dev.mysbx.herdr.package`).
  herdr,
}:
let
  muxLib = import ./mux-entry-lib.nix { inherit lib; };

  # Deliberately minimal: the keybinding mirror of
  # ../../programs/programs.herdr.nix belongs to the HOST configuration, and
  # duplicating it here would make two files drift. What the sandbox
  # needs is a config that (a) does not run the onboarding wizard and
  # (b) opens new tabs in the focused pane's directory, i.e. the repo.
  # `[worktrees] directory` is appended at RUN time (see the script):
  # the sibling path is a fact of the repo, discovered like
  # `Repo::worktrees` discovers it, never a store-path constant.
  sessionConfig = ''
    # Generated by myconfig for the mysbx sandbox — do not edit.
    onboarding = false

    [terminal]
    new_cwd = "follow"
  '';
in
writeShellApplication {
  name = "mysbx-herdr-entry";
  runtimeInputs = [
    herdr
    tmux
    coreutils
    bashInteractive
    jq
  ];
  text = ''
    ${muxLib.requireSocketDir "mysbx-herdr-entry"}
    ${muxLib.pinShell (lib.getExe bashInteractive)}

    # Fresh on every start, in the tmpfs HOME: a stale session config
    # is impossible, and nothing of the host's ~/.config/herdr is read.
    mkdir -p "$HOME/.config/herdr"
    cat ${builtins.toFile "mysbx-herdr-config.toml" sessionConfig} \
      > "$HOME/.config/herdr/config.toml"

    # herdr's FIRST workspace is always rooted at `$HOME`: the
    # `new_cwd` policy only applies to workspaces created later, and
    # there is no CLI flag for the initial one. Inside the sandbox
    # `$HOME` is the tmpfs (D14), so this would drop the operator into
    # an empty directory instead of the repository mysbx `--chdir`ed
    # into. Fix it up over the socket API: once herdr is up, create a workspace rooted at the repo,
    # focus it, and close the one that existed before. Runs in the
    # background because the API only answers after herdr has started,
    # and discards all output because the TUI owns the terminal from
    # here on. Same mechanism, and the same reason, as the bubblewrap
    # jail tier (../../programs.herdr.nix, `herdr-jail-entry`).
    repo_root="$PWD"

    # Point herdr's worktree root at the workmux sibling — placed here,
    # before `exec`, so it is configured once at session start. The
    # `-d` test is the BIND test: the argv builder mounts the sibling
    # rw at its real host path only when it exists (repo.rs
    # `Repo::worktrees`), so a visible directory is a writable one, and
    # an absent one keeps the key unset — mysbx's "a run never creates
    # the sibling" guard (config.md D13) is preserved: the script
    # configures, it never `mkdir`s.
    worktrees="$(dirname "$repo_root")/$(basename "$repo_root")__worktrees"
    if [ -d "$worktrees" ]; then
        # The path goes into a TOML basic string, so `\` and `"` must
        # be escaped and control characters (which TOML forbids there)
        # rejected — otherwise a repository name containing them yields
        # a config herdr cannot parse, and herdr then silently FALLS
        # BACK TO ITS DEFAULT (`~/.herdr/worktrees`), quietly losing
        # the repository-local root.
        case $worktrees in
            *[[:cntrl:]]*)
                echo "mysbx-herdr-entry: repository path contains control characters:" >&2
                echo "mysbx-herdr-entry: $worktrees — herdr keeps its worktree default" >&2
                ;;
            *)
                worktrees_toml="''${worktrees//\\/\\\\}"
                worktrees_toml="''${worktrees_toml//\"/\\\"}"
                printf '\n[worktrees]\ndirectory = "%s"\n' "$worktrees_toml" \
                    >> "$HOME/.config/herdr/config.toml"
                ;;
        esac
    else
        # No sibling: herdr's worktree actions fall back to herdr's own
        # default (`~/.herdr/worktrees`), which is the sandbox's tmpfs
        # home and therefore ephemeral — the same outcome `workmux add`
        # has here, said out loud once before the TUI owns the screen.
        echo "mysbx-herdr-entry: no $worktrees — it is not created here (mysbx config.md D13);" >&2
        echo "mysbx-herdr-entry: herdr worktrees use herdr's default until the sibling exists on the host" >&2
    fi

    (
        initial_ws=()
        for _ in $(seq 1 100); do
            if out="$(herdr workspace list 2>/dev/null)"; then
                mapfile -t initial_ws < <(
                    printf '%s' "$out" |
                        jq -r '.result.workspaces[].workspace_id' 2>/dev/null
                )
                if [ "''${#initial_ws[@]}" -gt 0 ]; then
                    break
                fi
            fi
            sleep 0.1
        done
        # No API answer (or no workspace yet) — leave herdr alone rather
        # than adding a second workspace to an unknown state.
        if [ "''${#initial_ws[@]}" -eq 0 ]; then
            exit 0
        fi
        herdr workspace create \
            --cwd "$repo_root" \
            --label "$(basename "$repo_root")" \
            --focus >/dev/null || exit 0
        for ws in "''${initial_ws[@]}"; do
            herdr workspace close "$ws" >/dev/null 2>&1 || true
        done
    ) >/dev/null 2>&1 &

    exec herdr "$@"
  '';

  meta = {
    description = "Interactive payload of a herdr-multiplexer mysbx sandbox";
    mainProgram = "mysbx-herdr-entry";
    platforms = lib.platforms.linux;
  };
}
