#!/usr/bin/env bash

THIS_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

case $1 in
    align)
        shift
        "$THIS_DIR/alignImages.sh" $@
        ;;
    stack)
        shift
        "$THIS_DIR/focusStackImages.sh" $@
        ;;
    crop)
        shift
        "$THIS_DIR/cropImages.sh" $@
        ;;
    init)
        shift
        "$THIS_DIR/initFotoDir.sh" $@
        ;;
    scale)
        shift
        "$THIS_DIR/scale-images-for-web.sh" $@
        ;;
    gallery)
        shift
        "$THIS_DIR/buildSimpleGallery.sh" $@
        ;;
    *)
        cat<<EOF
usage:
  align ... [imgs]
  stack ... [imgs]
  crop ... [imgs]
  init [dirToImport]
  scale [imgs]
  gallery [imgs]

################################################################################
align:
$("$THIS_DIR/alignImages.sh" --help)

################################################################################
stack:
$("$THIS_DIR/focusStackImages.sh" --help)

################################################################################
crop:
$("$THIS_DIR/cropImages.sh" --help)

################################################################################
scale:
$("$THIS_DIR/scale-images-for-web.sh" --help)

################################################################################
gallery:
$("$THIS_DIR/buildSimpleGallery.sh" --help)
EOF
        ;;
esac
