# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bro-skill = {
    pname = "bro-skill";
    version = "3aa8c40b1241111f73ab5360e770f7512193a20e";
    src = fetchFromGitHub {
      owner = "luchasarie";
      repo = "bro-skill";
      rev = "3aa8c40b1241111f73ab5360e770f7512193a20e";
      fetchSubmodules = false;
      sha256 = "sha256-LrkDPQQs/9nBkEf1ozB/oi320FMtin1BZcrTFBiKds0=";
    };
    date = "2026-08-26";
  };
  grafana-skills = {
    pname = "grafana-skills";
    version = "05196628fa1a6a557fad1a5623156170693607eb";
    src = fetchFromGitHub {
      owner = "grafana";
      repo = "skills";
      rev = "05196628fa1a6a557fad1a5623156170693607eb";
      fetchSubmodules = false;
      sha256 = "sha256-y4e2j8S+KlWntXrZxfBCh/tlFcEEmdqrf/BIPTEvy38=";
    };
    date = "2026-09-15";
  };
  litellm-grafana-dashboard = {
    pname = "litellm-grafana-dashboard";
    version = "1cac8bd9ab0bec8d5b6beb57669ad86ab4319c80";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/BerriAI/litellm/1cac8bd9ab0bec8d5b6beb57669ad86ab4319c80/cookbook/litellm_proxy_server/grafana_dashboard/dashboard_v2/grafana_dashboard.json";
      name = "litellm-grafana-dashboard.json";
      sha256 = "sha256-BepW78CWd6K27AL0nrIamyTESsVKsY/5/kO67QNU6vA=";
    };
    date = "2026-09-21";
  };
  pi-token-speed = {
    pname = "pi-token-speed";
    version = "2c7e5be62ffdc88e417394611498410acdce847d";
    src = fetchFromGitHub {
      owner = "gsanhueza";
      repo = "pi-token-speed";
      rev = "2c7e5be62ffdc88e417394611498410acdce847d";
      fetchSubmodules = false;
      sha256 = "sha256-5qrkxL0Ae3MhNbtNKS675Ju175EEPMCpdiWuB1UBSTQ=";
    };
    date = "2026-09-13";
  };
  simple-english = {
    pname = "simple-english";
    version = "79b590fc8596523d92c26b1ea7e33236606ef069";
    src = fetchFromGitHub {
      owner = "AminBlg";
      repo = "SimpleEnglish";
      rev = "79b590fc8596523d92c26b1ea7e33236606ef069";
      fetchSubmodules = false;
      sha256 = "sha256-CPD3x2wcU7INpOpqn0Hg4iY9gB1BAfuHU8e9w//s1sA=";
    };
    date = "2026-09-16";
  };
}
