# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bro-skill = {
    pname = "bro-skill";
    version = "3aa8c40b1241111f73ab5360e770f7512193a20e";
    src = fetchFromGitHub {
      owner = "luchasarie";
      repo = "bro-skill";
      rev = "3aa8c40b1241111f73ab5360e770f7512193a20e";
      fetchSubmodules = false;
      sha256 = "sha256-LrkDPQQs/9nBkEf1ozB/oi320FMtin1BZcrTFBiKds0=";
    };
    date = "2026-08-26";
  };
  grafana-skills = {
    pname = "grafana-skills";
    version = "1ccacf29049fde66637fe01ab93a83a772da323b";
    src = fetchFromGitHub {
      owner = "grafana";
      repo = "skills";
      rev = "1ccacf29049fde66637fe01ab93a83a772da323b";
      fetchSubmodules = false;
      sha256 = "sha256-zkgIRXkk4nSmVRKZ+LnJzqjp9fnQZSzLyh7pSwv7Umc=";
    };
    date = "2026-09-22";
  };
  litellm-grafana-dashboard = {
    pname = "litellm-grafana-dashboard";
    version = "02f61c9c420b9aa9de10ff673098ad7132b78f5b";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/BerriAI/litellm/02f61c9c420b9aa9de10ff673098ad7132b78f5b/cookbook/litellm_proxy_server/grafana_dashboard/dashboard_v2/grafana_dashboard.json";
      name = "litellm-grafana-dashboard.json";
      sha256 = "sha256-BepW78CWd6K27AL0nrIamyTESsVKsY/5/kO67QNU6vA=";
    };
    date = "2026-10-05";
  };
  pi-token-speed = {
    pname = "pi-token-speed";
    version = "b708faf217fb139c51cf8f8df0ca9c4050e489c8";
    src = fetchFromGitHub {
      owner = "gsanhueza";
      repo = "pi-token-speed";
      rev = "b708faf217fb139c51cf8f8df0ca9c4050e489c8";
      fetchSubmodules = false;
      sha256 = "sha256-o58k3OJQPVTQ5rSGvpk+bnCdFz6e28IE9lZY949nQa0=";
    };
    date = "2026-10-03";
  };
  simple-english = {
    pname = "simple-english";
    version = "32ea2d3f4404bfbff162c1861e5ae4f1bcc628b3";
    src = fetchFromGitHub {
      owner = "AminBlg";
      repo = "SimpleEnglish";
      rev = "32ea2d3f4404bfbff162c1861e5ae4f1bcc628b3";
      fetchSubmodules = false;
      sha256 = "sha256-mWs9n465FMiMcyxD9diTV6olXWuTy2wW+bZ475Vc3to=";
    };
    date = "2026-09-30";
  };
}
