# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  grafana-skills = {
    pname = "grafana-skills";
    version = "d9dfb9ec7a6b1ac6c8ec9741ec045ad6f412dec6";
    src = fetchFromGitHub {
      owner = "grafana";
      repo = "skills";
      rev = "d9dfb9ec7a6b1ac6c8ec9741ec045ad6f412dec6";
      fetchSubmodules = false;
      sha256 = "sha256-blw2Xpo1IzS5EfYC4TBRQj6ozRJPWe+8vGtz+GaDpts=";
    };
    date = "2026-08-05";
  };
  litellm-grafana-dashboard = {
    pname = "litellm-grafana-dashboard";
    version = "ead62528e607b9d8e61273def638799c9c3a69ba";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/BerriAI/litellm/ead62528e607b9d8e61273def638799c9c3a69ba/cookbook/litellm_proxy_server/grafana_dashboard/dashboard_v2/grafana_dashboard.json";
      name = "litellm-grafana-dashboard.json";
      sha256 = "sha256-EteGQo3xd5GvvkjKre7wqOZ6Hr/Yty78VZe6le55Zcw=";
    };
    date = "2026-08-04";
  };
}
