# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      options = [ "defaults" "size=25%" "mode=755" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/be770722-a525-4f6f-a873-ac20cd59fa44";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  boot.initrd.luks.devices."enc-pv".device = "/dev/disk/by-uuid/4837f94e-1fce-40e2-a173-5f8bb972eab4";

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/be770722-a525-4f6f-a873-ac20cd59fa44";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/be770722-a525-4f6f-a873-ac20cd59fa44";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/persistent" =
    { device = "/dev/disk/by-uuid/be770722-a525-4f6f-a873-ac20cd59fa44";
      fsType = "btrfs";
      options = [ "subvol=@persistent" ];
      neededForBoot = true;
    };

  fileSystems."/.swapfile" =
    { device = "/dev/disk/by-uuid/be770722-a525-4f6f-a873-ac20cd59fa44";
      fsType = "btrfs";
      options = [ "subvol=@swapfile" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp192s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
