# Copyright 2026 Maximilian Huber <oss@maximilian-huber.de>
# SPDX-License-Identifier: MIT
#
# Local LiteLLM proxy on f13. Listens on localhost:4000 and forwards
# all model requests to thing's LiteLLM via vserver's Caddy reverse
# proxy (litellm.thing.vserver.wg0.maxhbr.local).
#
# The proxy requires no authentication (no master_key is configured, so
# LiteLLM does not enforce API keys). This allows agent users —
# including the network-isolated "offline" agent, which can only reach
# loopback — to use AI models without credentials. The LiteLLM service
# runs as a dynamic system user, so its outbound requests to vserver
# are not subject to the offline agent's iptables egress block.
#
# Model names match those published by thing's LiteLLM (e.g.
# "gfx1151:hermes", "hermes", "opencode", …) so that tools and agents
# configured for thing work unchanged against this local proxy.
#
# Later, additional external services can be added by extending the
# model_list below.
{ config, lib, ... }:
let
  # Model names published by thing's LiteLLM, as registered in
  # myconfig.ai.localModels by hosts/shared.localModels.litellm.nix.
  litellmProviders = builtins.filter (
    m: m.name or null == "litellm.thing.wg0"
  ) config.myconfig.ai.localModels;
  models =
    if litellmProviders != [ ] then
      map (m: if builtins.isAttrs m then m.name else m) (builtins.head litellmProviders).models
    else
      [ ];

  # Upstream: vserver's Caddy reverse proxy, which forwards to thing's
  # LiteLLM. The hostname resolves to vserver's wg0 IP via /etc/hosts
  # (see modules/myconfig.deployedServices/default.nix).
  upstreamApiBase = "http://litellm.thing.vserver.wg0.maxhbr.local:80/v1";

  mkForwardEntry = modelName: {
    model_name = modelName;
    litellm_params = {
      model = "openai/${modelName}";
      api_base = upstreamApiBase;
      api_key = "not-needed";
      request.allowPrivateNetwork = true;
    };
  };
in
{
  config = {
    services.litellm = {
      enable = true;
      # Override the model_list generated by
      # modules/myconfig.ai/services.litellm.nix (which prefixes every
      # model name with the provider name) with pass-through entries
      # that forward the raw model names to vserver.
      settings.model_list = lib.mkForce (map mkForwardEntry models);
    };
  };
}
