# Compose file which enables emulation out of the box for non-AArch64 systems.
# 
# Comes out with sane defaults, feel free to configure as needed.

version: "3"

services:
  # This is the first container and image, responsible for setting up QEMU. In the future, this
  # can be replaced with `multiarch/qemu-user-static` when it supports at least QEMU 5.0.
  setup-qemu:
    image: qemu-handler
    build:
      context: setup-qemu
      args:
        QEMU_PKG_URL: "https://download-ib01.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/q/qemu-user-static-5.0.0-2.fc33.x86_64.rpm"
        QEMU_PKG_HASH: "f10098e4ece3f419c0e5883b7b9de01f7cfe376c272c576ef8553118d7ef9511"
        IMAGE_BASE: $IMAGE_BASE
    privileged: true
  # Main container, requires no elevated privileges to run. Builds NixOS.
  build-nixos:
    depends_on:
      - setup-qemu
  # Cleanup. Waits until `build-nixos` is done via a TCP socket, then cleans up any `binfmt_misc`
  # handler registered to QEMU.
  cleanup-qemu:
    image: qemu-handler
    environment:
      QEMU_CLEANUP: "y"
    privileged: true
    depends_on:
      - build-nixos
