# This file has been generated by node2nix 1.2.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "bezier-js-2.2.3" = {
      name = "bezier-js";
      packageName = "bezier-js";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bezier-js/-/bezier-js-2.2.3.tgz";
        sha1 = "c5574116a4a3564a71538d73e0b0d515da8ddec5";
      };
    };
    "caryll-shapeops-0.2.1" = {
      name = "caryll-shapeops";
      packageName = "caryll-shapeops";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/caryll-shapeops/-/caryll-shapeops-0.2.1.tgz";
        sha1 = "b8404ca50e6900c07abc9357b9bb0085b4046bcb";
      };
    };
    "cubic2quad-1.1.0" = {
      name = "cubic2quad";
      packageName = "cubic2quad";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cubic2quad/-/cubic2quad-1.1.0.tgz";
        sha1 = "78abec71b1b0244fdca863910ced8e07446a90e7";
      };
    };
    "libspiro-js-0.3.1" = {
      name = "libspiro-js";
      packageName = "libspiro-js";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/libspiro-js/-/libspiro-js-0.3.1.tgz";
        sha1 = "86652b0009a6d84ea79a5320bdca5f00612ee439";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "otfcc-c2q-0.5.0" = {
      name = "otfcc-c2q";
      packageName = "otfcc-c2q";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/otfcc-c2q/-/otfcc-c2q-0.5.0.tgz";
        sha1 = "ff8961236a36ee99244b07ec16531e941f0afde1";
      };
    };
    "patel-0.32.1" = {
      name = "patel";
      packageName = "patel";
      version = "0.32.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/patel/-/patel-0.32.1.tgz";
        sha1 = "9e70b6b23fd7a9c82c579ed591b8afa5217e6212";
      };
    };
    "toml-2.3.2" = {
      name = "toml";
      packageName = "toml";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/toml/-/toml-2.3.2.tgz";
        sha1 = "5eded5ca42887924949fd06eb0e955656001e834";
      };
    };
    "topsort-0.0.2" = {
      name = "topsort";
      packageName = "topsort";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/topsort/-/topsort-0.0.2.tgz";
        sha1 = "2e5e0ee8a1439417f101d5b9b2d035e620263321";
      };
    };
    "unorm-1.4.1" = {
      name = "unorm";
      packageName = "unorm";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unorm/-/unorm-1.4.1.tgz";
        sha1 = "364200d5f13646ca8bcd44490271335614792300";
      };
    };
    "yargs-7.1.0" = {
      name = "yargs";
      packageName = "yargs";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-7.1.0.tgz";
        sha1 = "6ba318eb16961727f5d284f8ea003e8d6154d0c8";
      };
    };
    "clipper-lib-1.0.0" = {
      name = "clipper-lib";
      packageName = "clipper-lib";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clipper-lib/-/clipper-lib-1.0.0.tgz";
        sha1 = "e902ceb26e28ee5cfa6014abdf790a51efff4ecb";
      };
    };
    "patrisika-0.21.0" = {
      name = "patrisika";
      packageName = "patrisika";
      version = "0.21.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/patrisika/-/patrisika-0.21.0.tgz";
        sha1 = "b82c27f7d4041522dc5c31b43b7c6efb19e47482";
      };
    };
    "escodegen-1.8.1" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.8.1.tgz";
        sha1 = "5a5b53af4693110bebb0867aa3430dd3b70a1018";
      };
    };
    "esmangle-1.0.1" = {
      name = "esmangle";
      packageName = "esmangle";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esmangle/-/esmangle-1.0.1.tgz";
        sha1 = "d9bb37b8f8eafbf4e6d4ed6b7aa2956abbd3c4c2";
      };
    };
    "yargs-6.6.0" = {
      name = "yargs";
      packageName = "yargs";
      version = "6.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-6.6.0.tgz";
        sha1 = "782ec21ef403345f830a808ca3d513af56065208";
      };
    };
    "resumer-0.0.0" = {
      name = "resumer";
      packageName = "resumer";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resumer/-/resumer-0.0.0.tgz";
        sha1 = "f1e8f461e4064ba39e82af3cdc2a8c893d076759";
      };
    };
    "patrisika-scopes-0.11.0" = {
      name = "patrisika-scopes";
      packageName = "patrisika-scopes";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/patrisika-scopes/-/patrisika-scopes-0.11.0.tgz";
        sha1 = "052a9d764a165e0b34cc35b6562a88242036b403";
      };
    };
    "estraverse-1.9.3" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-1.9.3.tgz";
        sha1 = "af67f2dc922582415950926091a4005d29c9bb44";
      };
    };
    "esutils-2.0.2" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.2.tgz";
        sha1 = "0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b";
      };
    };
    "esprima-2.7.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-2.7.3.tgz";
        sha1 = "96e3b70d5779f6ad49cd032673d1c312767ba581";
      };
    };
    "optionator-0.8.2" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz";
        sha1 = "364c5e409d3f4d6301d6c0b4c05bba50180aeb64";
      };
    };
    "source-map-0.2.0" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.2.0.tgz";
        sha1 = "dab73fbcfc2ba819b4de03bd6f6eaa48164b3f9d";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha1 = "4a5282ac164729e93619bcfd3ad151f817ce91f5";
      };
    };
    "esutils-1.0.0" = {
      name = "esutils";
      packageName = "esutils";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-1.0.0.tgz";
        sha1 = "8151d358e20c8acc7fb745e7472c0025fe496570";
      };
    };
    "esshorten-1.1.1" = {
      name = "esshorten";
      packageName = "esshorten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esshorten/-/esshorten-1.1.1.tgz";
        sha1 = "174f96b7cc267e46872d814e7db7c290bdff61a9";
      };
    };
    "estraverse-1.5.1" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-1.5.1.tgz";
        sha1 = "867a3e8e58a9f84618afb6c2ddbcd916b7cbaf71";
      };
    };
    "escope-1.0.3" = {
      name = "escope";
      packageName = "escope";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escope/-/escope-1.0.3.tgz";
        sha1 = "759dce8496c4248fec2d0caaf4108bcf3f1a7f5d";
      };
    };
    "source-map-0.1.43" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.1.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz";
        sha1 = "c24bc146ca517c1471f5dacbe2571b2b7f9e3346";
      };
    };
    "escodegen-1.3.3" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.3.3.tgz";
        sha1 = "f024016f5a88e046fd12005055e939802e6c5f23";
      };
    };
    "optionator-0.3.0" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.3.0.tgz";
        sha1 = "9715a8b5f5e7586cff06c8249e039cd7364d3f54";
      };
    };
    "esprima-1.1.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-1.1.1.tgz";
        sha1 = "5b6f1547f4d102e670e140c509be6771d6aeb549";
      };
    };
    "estraverse-4.1.1" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.1.1.tgz";
        sha1 = "f6caca728933a850ef90661d0e17982ba47111a2";
      };
    };
    "estraverse-2.0.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-2.0.0.tgz";
        sha1 = "5ae46963243600206674ccb24a09e16674fcdca1";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "levn-0.2.5" = {
      name = "levn";
      packageName = "levn";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.2.5.tgz";
        sha1 = "ba8d339d0ca4a610e3a3f145b9caf48807155054";
      };
    };
    "fast-levenshtein-1.0.7" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-1.0.7.tgz";
        sha1 = "0178dcdee023b92905193af0959e8a7639cfdcb9";
      };
    };
    "camelcase-3.0.0" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-3.0.0.tgz";
        sha1 = "32fc4b9fcdaf845fcdf7e73bb97cac2261f0ab0a";
      };
    };
    "cliui-3.2.0" = {
      name = "cliui";
      packageName = "cliui";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-3.2.0.tgz";
        sha1 = "120601537a916d29940f934da3b48d585a39213d";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "get-caller-file-1.0.2" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-1.0.2.tgz";
        sha1 = "f702e63127e7e231c160a80c1554acb70d5047e5";
      };
    };
    "os-locale-1.4.0" = {
      name = "os-locale";
      packageName = "os-locale";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-locale/-/os-locale-1.4.0.tgz";
        sha1 = "20f9f17ae29ed345e8bde583b13d2009803c14d9";
      };
    };
    "read-pkg-up-1.0.1" = {
      name = "read-pkg-up";
      packageName = "read-pkg-up";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg-up/-/read-pkg-up-1.0.1.tgz";
        sha1 = "9d63c13276c065918d57f002a57f40a1b643fb02";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha1 = "8c64ad5fd30dab1c976e2344ffe7f792a6a6df42";
      };
    };
    "require-main-filename-1.0.1" = {
      name = "require-main-filename";
      packageName = "require-main-filename";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-main-filename/-/require-main-filename-1.0.1.tgz";
        sha1 = "97f717b69d48784f5f526a6c5aa8ffdda055a4d1";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "which-module-1.0.0" = {
      name = "which-module";
      packageName = "which-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-module/-/which-module-1.0.0.tgz";
        sha1 = "bba63ca861948994ff307736089e3b96026c2a4f";
      };
    };
    "y18n-3.2.1" = {
      name = "y18n";
      packageName = "y18n";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-3.2.1.tgz";
        sha1 = "6d15fba884c08679c0d77e88e7759e811e07fa41";
      };
    };
    "yargs-parser-4.2.1" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-4.2.1.tgz";
        sha1 = "29cceac0dc4f03c6c87b4a9f217dd18c9f74871c";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "wrap-ansi-2.1.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-2.1.0.tgz";
        sha1 = "d8fc3d284dd05794fe84973caecdd1cf824fdd85";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "lcid-1.0.0" = {
      name = "lcid";
      packageName = "lcid";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lcid/-/lcid-1.0.0.tgz";
        sha1 = "308accafa0bc483a3867b4b6f2b9506251d1b835";
      };
    };
    "invert-kv-1.0.0" = {
      name = "invert-kv";
      packageName = "invert-kv";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/invert-kv/-/invert-kv-1.0.0.tgz";
        sha1 = "104a8e4aaca6d3d8cd157a8ef8bfab2d7a3ffdb6";
      };
    };
    "find-up-1.1.2" = {
      name = "find-up";
      packageName = "find-up";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-1.1.2.tgz";
        sha1 = "6b2e9822b1a2ce0a60ab64d610eccad53cb24d0f";
      };
    };
    "read-pkg-1.1.0" = {
      name = "read-pkg";
      packageName = "read-pkg";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg/-/read-pkg-1.1.0.tgz";
        sha1 = "f5ffaa5ecd29cb31c0474bca7d756b6bb29e3f28";
      };
    };
    "path-exists-2.1.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-2.1.0.tgz";
        sha1 = "0feb6c64f0fc518d9a754dd5efb62c7022761f4b";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "load-json-file-1.1.0" = {
      name = "load-json-file";
      packageName = "load-json-file";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-json-file/-/load-json-file-1.1.0.tgz";
        sha1 = "956905708d58b4bab4c2261b04f59f31c99374c0";
      };
    };
    "normalize-package-data-2.3.6" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.3.6.tgz";
        sha1 = "498fa420c96401f787402ba21e600def9f981fff";
      };
    };
    "path-type-1.1.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-1.1.0.tgz";
        sha1 = "59c44f7ee491da704da415da5a4070ba4f8fe441";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "parse-json-2.2.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-2.2.0.tgz";
        sha1 = "f480f40434ef80741f8469099f8dea18f55a4dc9";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "strip-bom-2.0.0" = {
      name = "strip-bom";
      packageName = "strip-bom";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom/-/strip-bom-2.0.0.tgz";
        sha1 = "6219a85616520491f35788bdbf1447a99c7e6b0e";
      };
    };
    "error-ex-1.3.1" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.1.tgz";
        sha1 = "f855a86ce61adc4e8621c3cda21e7a7612c3a8dc";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-utf8-0.2.1" = {
      name = "is-utf8";
      packageName = "is-utf8";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-utf8/-/is-utf8-0.2.1.tgz";
        sha1 = "4b0da1442104d1b336340e80797e865cf39f7d72";
      };
    };
    "hosted-git-info-2.4.2" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.4.2.tgz";
        sha1 = "0076b9f46a270506ddbaaea56496897460612a67";
      };
    };
    "is-builtin-module-1.0.0" = {
      name = "is-builtin-module";
      packageName = "is-builtin-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-builtin-module/-/is-builtin-module-1.0.0.tgz";
        sha1 = "540572d34f7ac3119f8f76c30cbc1b1e037affbe";
      };
    };
    "semver-5.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz";
        sha1 = "9b2ce5d3de02d17c6012ad326aa6b4d0cf54f94f";
      };
    };
    "validate-npm-package-license-3.0.1" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.1.tgz";
        sha1 = "2804babe712ad3379459acfbe24746ab2c303fbc";
      };
    };
    "builtin-modules-1.1.1" = {
      name = "builtin-modules";
      packageName = "builtin-modules";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-modules/-/builtin-modules-1.1.1.tgz";
        sha1 = "270f076c5a72c02f5b65a47df94c5fe3a278892f";
      };
    };
    "spdx-correct-1.0.2" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-1.0.2.tgz";
        sha1 = "4b3073d933ff51f3912f03ac5519498a4150db40";
      };
    };
    "spdx-expression-parse-1.0.4" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-1.0.4.tgz";
        sha1 = "9bdf2f20e1f40ed447fbe273266191fced51626c";
      };
    };
    "spdx-license-ids-1.2.2" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-1.2.2.tgz";
        sha1 = "c9df7a3424594ade6bd11900d596696dc06bac57";
      };
    };
    "code-point-at-1.1.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.1.0.tgz";
        sha1 = "0d070b4d043a5bea33a2f1a40e2edb3d9a4ccf77";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "yargs-parser-5.0.0" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-5.0.0.tgz";
        sha1 = "275ecf0d7ffe05c77e64e7c86e4cd94bf0e1228a";
      };
    };
  };
  args = {
    name = "iosevka";
    packageName = "iosevka";
    version = "1.9.2";
    src = ./.;
    dependencies = [
      sources."bezier-js-2.2.3"
      (sources."caryll-shapeops-0.2.1" // {
        dependencies = [
          sources."clipper-lib-1.0.0"
        ];
      })
      sources."cubic2quad-1.1.0"
      sources."libspiro-js-0.3.1"
      sources."object-assign-4.1.1"
      sources."otfcc-c2q-0.5.0"
      (sources."patel-0.32.1" // {
        dependencies = [
          (sources."patrisika-0.21.0" // {
            dependencies = [
              sources."patrisika-scopes-0.11.0"
            ];
          })
          (sources."escodegen-1.8.1" // {
            dependencies = [
              sources."estraverse-1.9.3"
              sources."esutils-2.0.2"
              sources."esprima-2.7.3"
              (sources."optionator-0.8.2" // {
                dependencies = [
                  sources."prelude-ls-1.1.2"
                  sources."deep-is-0.1.3"
                  sources."wordwrap-1.0.0"
                  sources."type-check-0.3.2"
                  sources."levn-0.3.0"
                  sources."fast-levenshtein-2.0.6"
                ];
              })
              (sources."source-map-0.2.0" // {
                dependencies = [
                  sources."amdefine-1.0.1"
                ];
              })
            ];
          })
          (sources."esmangle-1.0.1" // {
            dependencies = [
              sources."esutils-1.0.0"
              (sources."esshorten-1.1.1" // {
                dependencies = [
                  sources."estraverse-4.1.1"
                  sources."esutils-2.0.2"
                ];
              })
              sources."estraverse-1.5.1"
              (sources."escope-1.0.3" // {
                dependencies = [
                  sources."estraverse-2.0.0"
                ];
              })
              (sources."source-map-0.1.43" // {
                dependencies = [
                  sources."amdefine-1.0.1"
                ];
              })
              sources."escodegen-1.3.3"
              (sources."optionator-0.3.0" // {
                dependencies = [
                  sources."prelude-ls-1.1.2"
                  sources."deep-is-0.1.3"
                  sources."wordwrap-0.0.3"
                  sources."type-check-0.3.2"
                  sources."levn-0.2.5"
                  sources."fast-levenshtein-1.0.7"
                ];
              })
              sources."esprima-1.1.1"
            ];
          })
          (sources."yargs-6.6.0" // {
            dependencies = [
              sources."camelcase-3.0.0"
              (sources."cliui-3.2.0" // {
                dependencies = [
                  (sources."strip-ansi-3.0.1" // {
                    dependencies = [
                      sources."ansi-regex-2.1.1"
                    ];
                  })
                  sources."wrap-ansi-2.1.0"
                ];
              })
              sources."decamelize-1.2.0"
              sources."get-caller-file-1.0.2"
              (sources."os-locale-1.4.0" // {
                dependencies = [
                  (sources."lcid-1.0.0" // {
                    dependencies = [
                      sources."invert-kv-1.0.0"
                    ];
                  })
                ];
              })
              (sources."read-pkg-up-1.0.1" // {
                dependencies = [
                  (sources."find-up-1.1.2" // {
                    dependencies = [
                      sources."path-exists-2.1.0"
                      (sources."pinkie-promise-2.0.1" // {
                        dependencies = [
                          sources."pinkie-2.0.4"
                        ];
                      })
                    ];
                  })
                  (sources."read-pkg-1.1.0" // {
                    dependencies = [
                      (sources."load-json-file-1.1.0" // {
                        dependencies = [
                          sources."graceful-fs-4.1.11"
                          (sources."parse-json-2.2.0" // {
                            dependencies = [
                              (sources."error-ex-1.3.1" // {
                                dependencies = [
                                  sources."is-arrayish-0.2.1"
                                ];
                              })
                            ];
                          })
                          sources."pify-2.3.0"
                          (sources."pinkie-promise-2.0.1" // {
                            dependencies = [
                              sources."pinkie-2.0.4"
                            ];
                          })
                          (sources."strip-bom-2.0.0" // {
                            dependencies = [
                              sources."is-utf8-0.2.1"
                            ];
                          })
                        ];
                      })
                      (sources."normalize-package-data-2.3.6" // {
                        dependencies = [
                          sources."hosted-git-info-2.4.2"
                          (sources."is-builtin-module-1.0.0" // {
                            dependencies = [
                              sources."builtin-modules-1.1.1"
                            ];
                          })
                          sources."semver-5.3.0"
                          (sources."validate-npm-package-license-3.0.1" // {
                            dependencies = [
                              (sources."spdx-correct-1.0.2" // {
                                dependencies = [
                                  sources."spdx-license-ids-1.2.2"
                                ];
                              })
                              sources."spdx-expression-parse-1.0.4"
                            ];
                          })
                        ];
                      })
                      (sources."path-type-1.1.0" // {
                        dependencies = [
                          sources."graceful-fs-4.1.11"
                          sources."pify-2.3.0"
                          (sources."pinkie-promise-2.0.1" // {
                            dependencies = [
                              sources."pinkie-2.0.4"
                            ];
                          })
                        ];
                      })
                    ];
                  })
                ];
              })
              sources."require-directory-2.1.1"
              sources."require-main-filename-1.0.1"
              sources."set-blocking-2.0.0"
              (sources."string-width-1.0.2" // {
                dependencies = [
                  sources."code-point-at-1.1.0"
                  (sources."is-fullwidth-code-point-1.0.0" // {
                    dependencies = [
                      sources."number-is-nan-1.0.1"
                    ];
                  })
                  (sources."strip-ansi-3.0.1" // {
                    dependencies = [
                      sources."ansi-regex-2.1.1"
                    ];
                  })
                ];
              })
              sources."which-module-1.0.0"
              sources."y18n-3.2.1"
              sources."yargs-parser-4.2.1"
            ];
          })
          (sources."resumer-0.0.0" // {
            dependencies = [
              sources."through-2.3.8"
            ];
          })
        ];
      })
      sources."toml-2.3.2"
      sources."topsort-0.0.2"
      sources."unorm-1.4.1"
      (sources."yargs-7.1.0" // {
        dependencies = [
          sources."camelcase-3.0.0"
          (sources."cliui-3.2.0" // {
            dependencies = [
              (sources."strip-ansi-3.0.1" // {
                dependencies = [
                  sources."ansi-regex-2.1.1"
                ];
              })
              sources."wrap-ansi-2.1.0"
            ];
          })
          sources."decamelize-1.2.0"
          sources."get-caller-file-1.0.2"
          (sources."os-locale-1.4.0" // {
            dependencies = [
              (sources."lcid-1.0.0" // {
                dependencies = [
                  sources."invert-kv-1.0.0"
                ];
              })
            ];
          })
          (sources."read-pkg-up-1.0.1" // {
            dependencies = [
              (sources."find-up-1.1.2" // {
                dependencies = [
                  sources."path-exists-2.1.0"
                  (sources."pinkie-promise-2.0.1" // {
                    dependencies = [
                      sources."pinkie-2.0.4"
                    ];
                  })
                ];
              })
              (sources."read-pkg-1.1.0" // {
                dependencies = [
                  (sources."load-json-file-1.1.0" // {
                    dependencies = [
                      sources."graceful-fs-4.1.11"
                      (sources."parse-json-2.2.0" // {
                        dependencies = [
                          (sources."error-ex-1.3.1" // {
                            dependencies = [
                              sources."is-arrayish-0.2.1"
                            ];
                          })
                        ];
                      })
                      sources."pify-2.3.0"
                      (sources."pinkie-promise-2.0.1" // {
                        dependencies = [
                          sources."pinkie-2.0.4"
                        ];
                      })
                      (sources."strip-bom-2.0.0" // {
                        dependencies = [
                          sources."is-utf8-0.2.1"
                        ];
                      })
                    ];
                  })
                  (sources."normalize-package-data-2.3.6" // {
                    dependencies = [
                      sources."hosted-git-info-2.4.2"
                      (sources."is-builtin-module-1.0.0" // {
                        dependencies = [
                          sources."builtin-modules-1.1.1"
                        ];
                      })
                      sources."semver-5.3.0"
                      (sources."validate-npm-package-license-3.0.1" // {
                        dependencies = [
                          (sources."spdx-correct-1.0.2" // {
                            dependencies = [
                              sources."spdx-license-ids-1.2.2"
                            ];
                          })
                          sources."spdx-expression-parse-1.0.4"
                        ];
                      })
                    ];
                  })
                  (sources."path-type-1.1.0" // {
                    dependencies = [
                      sources."graceful-fs-4.1.11"
                      sources."pify-2.3.0"
                      (sources."pinkie-promise-2.0.1" // {
                        dependencies = [
                          sources."pinkie-2.0.4"
                        ];
                      })
                    ];
                  })
                ];
              })
            ];
          })
          sources."require-directory-2.1.1"
          sources."require-main-filename-1.0.1"
          sources."set-blocking-2.0.0"
          (sources."string-width-1.0.2" // {
            dependencies = [
              sources."code-point-at-1.1.0"
              (sources."is-fullwidth-code-point-1.0.0" // {
                dependencies = [
                  sources."number-is-nan-1.0.1"
                ];
              })
              (sources."strip-ansi-3.0.1" // {
                dependencies = [
                  sources."ansi-regex-2.1.1"
                ];
              })
            ];
          })
          sources."which-module-1.0.0"
          sources."y18n-3.2.1"
          sources."yargs-parser-5.0.0"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}