# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5f92b838-729d-4d32-8c49-941c0b457372";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."enc-pv".device = "/dev/disk/by-uuid/46fc7672-6bcc-4245-8d73-65c81cda0c58";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5f92b838-729d-4d32-8c49-941c0b457372";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/5f92b838-729d-4d32-8c49-941c0b457372";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/.swapfile" =
    { device = "/dev/disk/by-uuid/5f92b838-729d-4d32-8c49-941c0b457372";
      fsType = "btrfs";
      options = [ "subvol=@swapfile" "compress=no" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BBBE-C340";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # High-DPI console
  console.font = lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
}
