# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{
  stdenv,
  buildGoPackage,
  fetchgit,
  fetchhg,
  fetchbzr,
  fetchsvn,
}:

buildGoPackage rec {
  name = "deflux-unstable-${version}";
  version = "2020-03-12";
  rev = "31b4f30e8140cfa316dadc2beca8ae7aa2930602";

  goPackagePath = "github.com/fasmide/deflux";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/fasmide/deflux";
    sha256 = "1dnqivmgcj4v34n72mk1ady8wf9x29cm88fxglk71z63wfjilcpq";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = { };
}
