# Copyright 2026 Maximilian Huber <oss@maximilian-huber.de>
# SPDX-License-Identifier: MIT
#
# `herdr` is an "Agent multiplexer that lives in your terminal"
# (https://herdr.dev, nixpkgs `legacyPackages.x86_64-linux.herdr`). It is a
# companion to the agentic coding harnesses, so it is installed whenever at
# least one agentic coding agent is enabled on this host. The harness set
# mirrors `./skills/default.nix` (opencode, codex, claude-code,
# pi-coding-agent) and is extended with the remaining agentic terminal coding
# agents (`qwen-code`, `github-copilot-cli`).
#
# The generated ~/.config/herdr/config.toml mirrors the user's tmux keybindings
# (modules/shell.programs.tmux/tmux.conf): ctrl+a prefix, alt+arrow pane focus,
# alt+shift+arrow tab switching, prefix+r reload, and new tabs inheriting the
# current directory. Run `herdr --default-config` for the full key reference.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  agenticCodingEnabled =
    (config.myconfig.ai.claude-code.enable or false)
    || (config.myconfig.ai.codex.enable or false)
    || (config.myconfig.ai.opencode.enable or false)
    || (config.myconfig.ai.pi-coding-agent.enable or false)
    || (config.myconfig.ai.qwen-code.enable or false)
    || (config.myconfig.ai.github-copilot-cli.enable or false);

  # Keybindings mirror ~/.tmux.conf (modules/shell.programs.tmux/tmux.conf).
  # Concept mapping: tmux window->herdr tab, tmux pane->herdr pane. Bindings
  # left unset here stay at herdr defaults, several of which already match tmux:
  #   setw -g mouse on          -> [ui] mouse_capture = true (herdr default)
  #   set -g base-index 1       -> herdr tabs are 1-indexed (switch_tab 1..9)
  #   status-keys/mode-keys vi  -> herdr navigate mode uses h/j/k/l by default
  # tmux's `bind-key C-a last-window` (toggle to previous window) has no herdr
  # equivalent (only last_pane exists), so it is not replicated.
  herdrConfig = ''
    # Generated by NixOS (modules/myconfig.ai/programs.herdr.nix).
    # Mirrors ~/.tmux.conf - do not edit by hand. After Nix changes, run
    # `herdr server reload-config` (or restart herdr) to pick them up.

    [terminal]
    # tmux: bind-key 'C' new-window -c '#{pane_current_path}'
    #       bind-key 'M-/' attach -c '#{pane_current_path}'
    # New tabs/panes/workspaces inherit the focused pane's directory.
    new_cwd = "follow"

    [keys]
    # tmux: set -g prefix C-a  (default is ctrl+b)
    prefix = "ctrl+a"

    # tmux: bind r source-file ~/.tmux.conf
    reload_config = "prefix+r"

    # tmux: bind-key 'C' new-window -c '#{pane_current_path}'
    # (with new_cwd = "follow" above, prefix+c already opens in the cwd)
    new_tab = "prefix+c"

    # tmux: bind -n M-Left/Right/Up/Down select-pane -L/-R/-U/-D
    # Direct bindings (no prefix) - matches tmux `bind -n`.
    focus_pane_left = "alt+left"
    focus_pane_down = "alt+down"
    focus_pane_up = "alt+up"
    focus_pane_right = "alt+right"

    # tmux: bind -n M-S-Left next-window
    next_tab = "alt+shift+left"
    # tmux: bind -n M-S-Right previous-window
    previous_tab = "alt+shift+right"
  '';
in
{
  config = lib.mkIf agenticCodingEnabled {
    home-manager.sharedModules = [
      {
        home.packages = with pkgs; [ herdr ];
        xdg.configFile."herdr/config.toml".text = herdrConfig;
      }
    ];
  };
}
