# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ ... }:

{
  fileSystems."/home/mhuber/Bilder/hdd" =
    { device = "/dev/disk/by-uuid/a462ff79-65d7-46ec-a68d-22282c8aafee";
      fsType = "ext4";
      options = ["auto,nofail,x-systemd.device-timeout=1,sync,users,rw,discard,noatime"];
    };
  fileSystems."/home/mhuber/Bilder/ssd" =
    { device = "/dev/disk/by-uuid/a63df934-7f65-46d9-9553-eef773e826ee";
      fsType = "ext4";
      options = ["auto,nofail,x-systemd.device-timeout=1,sync,users,rw,discard,noatime"];
    };
}
