# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ ... }:

{
  services.syncthing = {
    enable = false;
    user = "mhuber";
    group = "mhuber";
    dataDir = "/home/mhuber/syncthing";
    openDefaultPorts = false;
  };
}
