# Copyright 2025 Maximilian Huber <oss@maximilian-huber.de>
# SPDX-License-Identifier: MIT
#
# myconfig.ai.microvm — Cloud Hypervisor agent-sandbox tier.
#
# A second, stronger isolation tier for autonomous coding agents, alongside
# the existing QEMU/SLiRP `flake.agent-qemu.nix` tier. It runs each agent
# session inside a Cloud Hypervisor microVM (via the `microvm.nix` flake
# input) with its own kernel, a disposable root/home, a single writable
# virtiofs `/workspace` mount (a standalone git clone), a dedicated private
# bridge, and model-API access restricted to the host LiteLLM proxy through a
# bridge-only forwarding endpoint. Every agent process and guest workload is
# treated as potentially hostile; the secure default prioritises isolation
# over convenience.
#
# PHASE 0 — this file only *defines the option namespace, assertions and
# registration*. It also instantiates the authoritative supported-agent
# registry (./agents.nix) EXACTLY ONCE and passes it to the sibling modules as
# `_module.args.agentRegistry`. The feature is disabled by default and, while
# disabled,
# produces no config side effects: it does NOT import the microvm.nix host
# module, create the bridge/firewall rules, define VM slots, build the guest,
# or register Workmux agents. Those are implemented in later phases inside
# guest.nix / network.nix / launcher.nix / workmux.nix. The option reference
# lives in `./docs/agent-microvm.md`.
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:
let
  cfg = config.myconfig.ai.microvm;

  # --- deterministic fixed slot pool (agent-<class>-0 .. ) ----------------
  # The slot table is generated by the shared helper in slots.nix — the same
  # helper guest.nix uses to actually build the VMs — so these uniqueness /
  # bound assertions (§37) always guard the exact table that builds the VMs.
  slotLib = import ./slots.nix { inherit lib; };
  slots = slotLib.mkSlots effectiveResourceClasses;
  slotIPs = map (s: s.ip) slots;
  slotMACs = map (s: s.mac) slots;
  slotCIDs = map (s: s.cid) slots;
  slotNames = map (s: s.name) slots;
  slotTaps = map (s: s.tap) slots;

  # --- ticket 5 A: fixed resource classes ---------------------------------
  # The pool is grouped into PREBUILT classes. The deprecated single-class
  # spelling (`slotCount` / `defaultVcpu` / `defaultMemoryMiB`) and its
  # ambiguity guard were removed together with the `full` profile: no host used
  # them, so a host that still sets one now gets an unknown-option error — which
  # is louder than the warning it replaces.
  effectiveResourceClasses = cfg.resourceClasses;

  # --- authoritative supported-agent registry -----------------------------
  # ./agents.nix is the SINGLE SOURCE OF TRUTH for the supported agents (guest
  # packages + guest env, guest `agent-run` dispatch, launcher validation +
  # help, workmux registrations). Instantiated EXACTLY ONCE here and handed to
  # the sibling modules through `_module.args.agentRegistry`, so every
  # consumer sees the same registry with the same context (endpoint, model)
  # and cannot re-instantiate it with different arguments.
  #
  # Its well-formedness errors are surfaced as NixOS assertions below, so a
  # malformed entry fails loudly here instead of producing a broken guest
  # closure or a launcher that accepts an agent the guest cannot run.

  # Which of the declared agents this host actually builds into its guests
  # (lightweight plan phase 2). `null` — the module-wide DEFAULT — keeps every
  # declared agent. That default is deliberate: everything agent-shaped (guest
  # closure, `agent-run` dispatch, batch dispatch, launcher validation, the
  # workmux `microvm-<agent>` panes) follows the selection, so a narrower
  # default would silently remove panes and reject `--agent <name>` invocations
  # that work today. The closure trade-off is explicit: every declared agent's
  # runtime is baked into every guest image, so a host that wants the
  # lightweight closure states the agents it actually uses (see
  # `hosts/host.f13/ai.f13.nix`).
  agentRegistry = import ./agents.nix {
    inherit lib pkgs inputs;
    enabledNames = cfg.enabledAgents;
    litellmPort = cfg.litellmPort;
    # Hermes cannot discover a model on its own; reuse the model name the host
    # `myconfig.ai.hermes` backends use (a LiteLLM route). Reading the option
    # (not `cfg`) keeps ONE model definition for host and sandbox alike.
    hermesModel = config.myconfig.ai.hermes.model.default;
  };

  # The registry the SIBLING MODULES actually receive. Identical to
  # `agentRegistry` above for every real host — it IS that value, read back
  # through the option — but the assertions below are deliberately written
  # against THIS one: an assertion that checked a different instance than the
  # guest closure, the launcher and the workmux panes are built from could pass
  # while those disagree with it. It is also what makes the registry-dependent
  # guards exercisable: tests/microvm.nix substitutes a registry whose
  # batch-capable subset is empty (a shape ./agents.nix cannot currently
  # produce, since every declared agent has `batchArgs`) and requires the
  # batch-capable-agent assertion to fire for a `batch` host and to stay silent
  # for an interactive-only one.
  #
  # CONTRACT for anyone who ever overrides `_module.args.agentRegistry` (only
  # tests/microvm.nix does today): the argument must NEVER be defined in terms of
  # `config.assertions` (directly or through a module that reads them). This is a
  # same-module read-back of an argument this module also DEFINES, so such a
  # definition would close the loop `assertions -> agentRegistry -> assertions`
  # into an infinite recursion. A plain value, or one derived from options other
  # than `assertions`, cannot recurse.
  effectiveRegistry = config._module.args.agentRegistry;

  # --- lightweight plan phase 5: the CAPABILITY SELECTOR -------------------
  # `capabilities` selects WHICH of the two execution capabilities a guest
  # carries. It is deliberately a SET over the ONE guest shape, not a
  # three-valued `interactive | batch | combined` mode: a `combined` value would
  # be a compatibility profile in disguise and would re-create exactly the
  # cross-product the `full`/`lite` collapse removed. The default is BOTH, i.e.
  # today's behaviour byte-for-byte.
  #
  # Resolved EXACTLY ONCE here and handed to the sibling modules through
  # `_module.args.agentCapabilities`, so ./session.nix (the layout table every
  # path/mode/tmpfiles rule/verifier line is generated from), ./job.nix,
  # ./hostkeys.nix, ./guest.nix, ./launcher.nix and ./workmux.nix all follow ONE
  # decision instead of each carrying its own `if`.
  #
  # `vsock` (lightweight plan phase 6) is a THIRD token, NOT a second guest
  # shape: it adds a VSOCK control channel (the `sshd-vsock@` unit, reused from
  # upstream `microvm.vsock.cid` + NixOS' systemd-ssh-generator) so a host that
  # narrows `interactive` away (a batch-only host, which has no TCP sshd) can
  # still be driven by `agent-microvm ssh` and the runtime-validation suite.
  #
  # IT IS NOT ADDITIVE. The token has TWO effects, and the second one REMOVES
  # configuration:
  #   1. always: the VSOCK control channel above;
  #   2. WHENEVER `networkProfile` is the (DEFAULT) `proxy-only`: it also selects
  #      the `vsock` MODEL TRANSPORT (../network-profiles.nix `resolveTransport`),
  #      which REPLACES the guest's network stack — no `microvm.interfaces` TAP,
  #      no static IP, no networkd, and on the HOST no private bridge, no TAP
  #      attach units, no `AGENT_MICROVM_*` firewall chains and no bridge-only
  #      LiteLLM socket. The model API instead travels the guest's unchanged
  #      `127.0.0.1:<litellmPort>` over AF_VSOCK to a per-VM host forwarder.
  # So adding `vsock` on a `proxy-only` host is exactly the plan's LITERAL
  # phase-6 objective, not a second guest shape: there is still ONE forwarder
  # unit (`litellm-forwarder`), ONE guest-visible endpoint and ONE resolved
  # transport. The decision lives in the SAME per-capability mechanism
  # the plan's own phase-5 deviation hardened the layout table for (a `vsock`
  # token was explicitly anticipated there), not in a `transport = "tap"|"vsock"`
  # enum that would re-create the cross-product the `full`/`lite` collapse
  # removed. Default OFF: the historical `[ "interactive" "batch" ]` is
  # unchanged, so every guest artefact of a default host is byte-for-byte as it
  # was.
  declaredCapabilities = [
    "interactive"
    "batch"
    "vsock"
  ];
  # Resolved DEFENSIVELY (membership tests, never a lookup that could throw), so
  # an unknown token is reported by the assertion below instead of failing
  # somewhere deep in a consumer.
  selectedCapabilities = lib.unique cfg.capabilities;
  unknownCapabilities = lib.filter (c: !(lib.elem c declaredCapabilities)) selectedCapabilities;
  # ONE list of tokens, ONE derivation of the per-capability booleans: the
  # booleans are GENERATED from `declaredCapabilities` (`lib.genAttrs`) rather
  # than written out a second time, so adding a token to that list cannot leave a
  # consumer's `agentCapabilities.<token>` undefined (which is a THROW, e.g. in
  # ./launcher.nix's `missingCapabilities` filter) and cannot go out of sync with
  # `declared`/`selected`.
  #
  # `declared` and `selected` are the two NON-token keys of the attrset. A
  # capability token spelled like either of them would be silently overwritten by
  # the `//` below (its boolean would become a list), so the `assert` makes that
  # mistake a hard eval error rather than a subtle mis-selection.
  agentCapabilities =
    assert lib.all (
      c:
      !(lib.elem c [
        "declared"
        "selected"
      ])
    ) declaredCapabilities;
    lib.genAttrs declaredCapabilities (c: lib.elem c selectedCapabilities)
    // {
      declared = declaredCapabilities;
      selected = lib.filter (c: lib.elem c selectedCapabilities) declaredCapabilities;
    };

  # --- ticket 3 C: network profiles ---------------------------------------
  # `network-profiles.nix` is the authoritative capability table; the effective
  # profile is resolved HERE and handed to network.nix / guest.nix through
  # `_module.args.agentNetwork`, so host firewall policy and guest-side proxy /
  # DNS configuration are derived from ONE decision.
  #
  # The deprecated booleans (`allowPublicInternet` / `allowPrivateNetworks` /
  # `allowInterVmTraffic`) and their translate/reject/warn migration were removed
  # together with the `full` profile: no host used them, so a host that still sets
  # one now gets an unknown-option error — which is louder than the assertion it
  # replaces, and cannot be mistaken for a capability that exists.
  profileLib = import ./network-profiles.nix { inherit lib; };

  effectiveProfile = cfg.networkProfile;

  # --- lightweight plan phase 6: the TRANSPORT decision -------------------
  # Resolved EXACTLY ONCE, here, from the table in ./network-profiles.nix and
  # handed to network.nix / guest.nix / session.nix / hostkeys.nix /
  # launcher.nix through the SAME `_module.args.agentNetwork` the profile
  # already travels in. `vsock` + the closed `proxy-only` profile REPLACES the
  # guest's network with an AF_VSOCK path to a per-VM host forwarder: no TAP, no
  # bridge, no static IP, no guest networkd, no host firewall chains. Every
  # consumer reads the transport's CAPABILITY FLAGS (`transportCaps`), never the
  # name, so there is one decision and no second code path.
  effectiveTransport = profileLib.resolveTransport {
    profile = effectiveProfile;
    vsockCapability = agentCapabilities.vsock;
  };
  effectiveTransportCaps = profileLib.forTransport effectiveTransport;

  agentNetwork = {
    profile = effectiveProfile;
    caps = profileLib.forProfile effectiveProfile;
    transport = effectiveTransport;
    transportCaps = effectiveTransportCaps;
    # Whether an SSH daemon bound to a guest NETWORK interface can be reached at
    # all. Derived HERE (once) rather than in each consumer, because it is a
    # NETWORK fact — under the `vsock` transport the guest has no interface, so a
    # TCP sshd would listen where nothing can connect. guest.nix suppresses the
    # TCP `sshd.service` accordingly, session.nix skips its mount ordering and
    # launcher.nix renders `SSH_ENABLED=0`, so the VSOCK `sshd-vsock@` is the ONE
    # control channel there.
    tapSshUsable = cfg.enableSsh && effectiveTransportCaps.tapSsh;
    # The AF_VSOCK port of the model forwarder (see `vsockLitellmPort` below):
    # part of the ONE resolved network decision, so the host forwarder
    # (network.nix) and the guest bridge (guest.nix) cannot disagree.
    inherit vsockLitellmPort;
    # Effective DNS policy for the `internet` profile: an empty `dnsServers`
    # means "the host itself on the bridge".
    dnsServers = if cfg.dnsServers == [ ] then [ cfg.gatewayAddress ] else cfg.dnsServers;
  };

  # The AF_VSOCK port the per-VM host forwarder listens on and the guest bridge
  # connects to (CID 2 = the host). Deliberately the SAME number as the TCP
  # `litellmPort`, so an operator reads one port everywhere; cloud-hypervisor
  # backs it with the Unix socket `<stateRoot>/<slot>/notify.vsock_<port>`.
  vsockLitellmPort = cfg.litellmPort;
  # microvm.nix reserves AF_VSOCK port 8888 for the systemd notify socket of a
  # cloud-hypervisor guest (its `notify.vsock_8888` socat bridge), so the model
  # forwarder must never claim it.
  reservedNotifyVsockPort = 8888;

  isAbsolutePath = p: lib.hasPrefix "/" p;
in
{
  imports = [
    ./config-seed.nix
    ./guest-shell-convenience.nix
    ./guest.nix
    ./guest-model-config.nix
    ./hostkeys.nix
    ./job.nix
    ./session.nix
    ./state.nix
    ./workspace.nix
    ./network.nix
    ./launcher.nix
    ./secrets.nix
    ./workmux.nix
  ];

  options.myconfig.ai.microvm = with lib; {
    enable = mkEnableOption "myconfig.ai.microvm (Cloud Hypervisor agent sandboxes)";

    enabledAgents = mkOption {
      type = types.nullOr (types.listOf types.str);
      default = null;
      example = literalExpression ''[ "codex" ]'';
      description = ''
        SELECTED coding agents (tokens of the authoritative registry in
        ./agents.nix). Everything agent-shaped is derived from this selection:
        the guest closure's agent packages and per-agent guest environment, the
        guest `agent-run` dispatch, the batch worker's dispatch, the host
        launcher's `--agent` validation and help text, the Workmux
        `microvm-*` registrations and the agent-state directories. A
        deselected agent is therefore ABSENT from the guest image, not merely
        hidden, and `--agent <name>` for it is rejected.

        `null` (the default) means EVERY declared agent — the historical
        behaviour, kept as the default so a host cannot silently lose a workmux
        `microvm-<agent>` pane or a `submit --agent <name>` it relies on. It is
        also the expensive choice: every declared agent's runtime is baked into
        every guest image, so a host that wants the lightweight guest closure
        should name the agents it actually uses. An unknown token is rejected at
        evaluation time.
      '';
    };

    capabilities = mkOption {
      type = types.listOf types.str;
      default = [
        "interactive"
        "batch"
      ];
      example = literalExpression ''[ "batch" ]'';
      description = ''
        Which CAPABILITIES the guests of this host carry (lightweight plan
        phase 5). A capability the host does not select is ABSENT — not
        merely hidden.

        The list mixes TWO KINDS of token, and the distinction is
        load-bearing:

        - the WORKLOAD capabilities `interactive` and `batch` decide WHAT the
          guest can be asked to do (be entered by an operator / be given a
          job). At least ONE of them must be selected — a guest with neither
          would boot, seed a home and idle forever;
        - the TRANSPORT capability `vsock` decides HOW the host reaches a
          guest (and, on a `proxy-only` host, how the model API reaches it).
          It carries no workload of its own, so it can NEVER be selected
          alone: `capabilities = [ "vsock" ]` is rejected at evaluation time
          rather than silently producing an undocumented interactive-ish
          guest.

        - `interactive` (WORKLOAD) — the SSH control channel (`enableSsh`), the per-slot
          SSH host identity and its read-only `hostkeys/` subdirectory, the
          known_hosts database, the guest `agent-run` entry point, the workmux
          `microvm-<agent>` panes and the launcher's `run` / `ssh`
          subcommands.
        - `batch` (WORKLOAD) — the TRUSTED guest job controller, the UNTRUSTED worker
          template, the guest job-protocol helpers, the `input/`,
          `controller/`, `worker/` and `worker-logs/` subdirectories of the
          session tree (and their host tmpfiles rules), the host-side result
          archive and the launcher's `submit` / `cancel` subcommands.
        - `vsock` (TRANSPORT) — a VSOCK control channel (lightweight plan phase 6): the
          guest gets a VSOCK device (`microvm.vsock.cid` = the slot's
          deterministic CID) and a VSOCK-only `sshd-vsock@` unit (SSH over
          AF_VSOCK, reused from upstream), reachable ONLY from the host (CID
          2) and NOT from any TCP/network interface. It is what lets a
          batch-only host — which has no `interactive` sshd — still be driven
          by `agent-microvm ssh` and the runtime-validation suite, closing
          the phase-5 coverage hole. The per-slot SSH host identity
          (`hostkeys/`) and its `known_hosts` entry are provisioned for
          `vsock` too, so the VSOCK channel is host-key-verified exactly like
          the TAP one.

          NOT ADDITIVE — on a `proxy-only` host (the DEFAULT profile) the
          `vsock` token ALSO SELECTS THE `vsock` MODEL TRANSPORT and thereby
          REMOVES the guest's network entirely: the guest gets no
          `microvm.interfaces` TAP, no static IPv4, no default route and no
          systemd-networkd, and the HOST builds no private bridge, no TAP
          attach/L2-isolate units, no `AGENT_MICROVM_*` firewall chains and no
          bridge-only LiteLLM socket. The model API still reaches the guest at
          the unchanged `127.0.0.1:<litellmPort>`, but over
          AF_VSOCK to a destination-fixed per-VM host forwarder instead of over
          the bridge, so no agent configuration changes. Under any other
          profile (`offline`, `package-access`, `internet`) the model transport
          stays `tap` and `vsock` really is only the extra control channel.

        Both `interactive` and `batch` (the default) is exactly the
        historical behaviour. `vsock` is OFF by default, so a default host's
        guest closure is byte-for-byte unchanged. The list is a SET, not an
        ordered preference, and there is deliberately no "combined" value:
        that would be a compatibility profile crossed with the one guest
        shape, which is what the `full`/`lite` collapse removed.

        An empty selection, a selection with NO workload capability (e.g. the
        transport-only `[ "vsock" ]`), an unknown token, `enableSsh` without
        the `interactive` capability, `vsock` without an `sshPublicKeyFile`,
        and `vsock` paired with an insecure network profile
        (`package-access`/`internet`) are rejected at evaluation time.
      '';
    };

    resourceClasses = mkOption {
      type = types.attrsOf (
        types.submodule {
          options = {
            count = mkOption {
              type = types.ints.positive;
              description = "Number of PREBUILT slots in this class.";
            };
            vcpu = mkOption {
              type = types.ints.positive;
              description = "vCPUs per guest in this class.";
            };
            memoryMiB = mkOption {
              type = types.ints.positive;
              description = "Guest RAM per guest in this class, in MiB.";
            };
          };
        }
      );
      default = {
        normal = {
          count = 4;
          vcpu = 4;
          memoryMiB = 8192;
        };
      };
      example = literalExpression ''
        {
          small  = { count = 2; vcpu = 2; memoryMiB = 4096; };
          normal = { count = 4; vcpu = 4; memoryMiB = 8192; };
          large  = { count = 1; vcpu = 8; memoryMiB = 16384; };
        }
      '';
      description = ''
        Fixed, PREBUILT resource classes. Each class contributes `count` slots
        named `agent-<class>-<i>` with the class's `vcpu` / `memoryMiB` sizing;
        every slot keeps its own deterministic TAP, MAC, IPv4, VSOCK CID, state
        directory, job directory and (with `enableSsh`) SSH host identity.

        There is deliberately NO per-job Nix evaluation: `submit`/`run` allocate
        from this fixed pool with `--resource-class <name>`, and the allocator
        only ever considers the requested class (it never silently substitutes
        a smaller one).

        NOTE (merge semantics): defining a single class, e.g.
        `resourceClasses.large = { … }`, MERGES with the default `normal` class
        rather than replacing it. Use `lib.mkForce { … }` to define the pool
        exhaustively.
      '';
    };

    bridgeName = mkOption {
      type = types.str;
      default = "agentbr0";
      description = "Name of the dedicated private bridge for agent microVMs.";
    };

    subnet = mkOption {
      type = types.str;
      default = "192.168.83.0/24";
      description = "IPv4 subnet (CIDR) of the private agent bridge.";
    };

    gatewayAddress = mkOption {
      type = types.str;
      default = "192.168.83.1";
      description = ''
        Host-side IPv4 address on the agent bridge. Also the address on
        which the bridge-only LiteLLM forwarding endpoint listens.
      '';
    };

    litellmPort = mkOption {
      type = types.port;
      default = 4000;
      description = ''
        TCP port of the host LiteLLM proxy. The guest reaches the model API
        only via <gatewayAddress>:<litellmPort>, forwarded to the
        loopback-only LiteLLM proxy on 127.0.0.1:<litellmPort>.
      '';
    };

    workspaceRoot = mkOption {
      type = types.str;
      default = "/var/lib/agent-microvms/workspaces";
      description = ''
        Absolute host path under which per-task standalone git clones are
        created. Exactly one clone is mounted read-write into a slot at
        /workspace.

        Clones are grouped one level down by the source repository, so a
        task's clone lives at
        `<workspaceRoot>/<repoSlug>__agent-microvm/<task>` rather than a flat
        `<workspaceRoot>/<task>`. `<repoSlug>` is a filesystem-safe slug of the
        cloned repository's git toplevel basename with the literal suffix
        `__agent-microvm` appended, mirroring the `<basename>__worktrees`
        convention used by workmux (../fns/workmux-worktree.nix). Two
        repositories therefore never share a clone directory, and one
        repository's tasks sit next to each other.

        Only used by `workspaceLayout = "central"` (the default). Under
        `beside-repo` no clone is created here, but the path stays meaningful:
        clones created by an earlier generation remain enumerable by `usage` /
        `dashboard` and removable by `workspace-remove`.
      '';
    };

    workspaceLayout = mkOption {
      type = types.enum [
        "central"
        "beside-repo"
      ];
      default = "central";
      description = ''
        Where a task's standalone clone is created (see
        ./docs/workspace-layout.md).

        `central` (the default) groups every clone under `workspaceRoot`:
        `<workspaceRoot>/<repoSlug>__agent-microvm/<task>`.

        `beside-repo` creates the group next to the SOURCE repository instead:
        a task of `/home/u/src/myrepo` lands in
        `/home/u/src/myrepo__agent-microvm/<task>`, mirroring the
        `<project>__worktrees` convention of workmux, so the clone a human has
        to diff / fetch from / merge back sits next to the repository it
        belongs to and is reachable without `sudo`.

        Independent of the layout, every clone is registered in the root-owned
        workspace index (`<runtimeRoot>/workspace-index/<task>`), which is what
        keeps the task-addressed commands (`workspace-remove`, `usage`,
        `dashboard`, `recover`) working when clones no longer share one root.

        `beside-repo` refuses a repository whose parent directory is `/` or
        which sits inside `runtimeRoot` / `stateRoot` / `workspaceRoot`: a
        guest-writable tree must never be created there.
      '';
    };

    runtimeRoot = mkOption {
      type = types.str;
      default = "/var/lib/agent-microvms";
      description = ''
        Absolute host path for agent-microvm runtime state (task metadata,
        locks, bind-mount sources). Must be an absolute path.
      '';
    };

    stateRoot = mkOption {
      type = types.str;
      default = "/var/lib/microvms";
      description = ''
        Absolute host path used by microvm.nix for per-VM state
        (/var/lib/microvms/<slot>). This is the path the launcher's VSOCK ssh
        target (`vsock-mux/<stateRoot>/<slot>/notify.vsock`), the per-slot
        `known_hosts` entry and the per-VM bind-mount source key on. It MUST
        equal `config.microvm.stateDir` (where microvm.nix actually puts
        per-VM state and where cloud-hypervisor backs the VSOCK device); an
        assertion below rejects a host that diverges them. Defaults to the same
        `/var/lib/microvms` as `microvm.stateDir`.
      '';
    };

    networkProfile = mkOption {
      type = types.enum profileLib.names;
      default = "proxy-only";
      description = ''
        Named, coherent guest network policy. It replaced the ambiguous
        `allowPublicInternet` / `allowPrivateNetworks` / `allowInterVmTraffic`
        booleans, which have since been REMOVED.

        - `offline`        only the control traffic required to manage the VM
                          (host -> guest SSH/console). No model API, no DNS,
                          no package proxy, no routing.
        - `proxy-only`     THE SECURE DEFAULT: additionally the bridge-only
                          LiteLLM endpoint <gatewayAddress>:<litellmPort>, and
                          nothing else.
        - `package-access` additionally ONE explicit host package-proxy port
                          (`packageProxyPort`), with http_proxy/https_proxy
                          pointed at it. Still no routing, NAT or DNS, so it
                          is NOT unrestricted internet.
        - `internet`       full functional egress: routing, NAT/masquerading,
                          an explicit DNS policy (`dnsServers`) and
                          rate-limited drop logging. INSECURE.

        In EVERY profile: guest-to-guest traffic is blocked (per-TAP L2
        `isolated` + IPv4 FORWARD DROP), and the cloud-metadata IP plus all
        private/special-use IPv4 ranges (host LAN, VPN peers, RFC1918, CGNAT,
        loopback, link-local, multicast, reserved) are dropped.

        `package-access` and `internet` require
        `acknowledgeInsecureNetwork = true`.

        See ./network-profiles.nix for the authoritative capability table.
      '';
    };

    packageProxyPort = mkOption {
      type = types.nullOr types.port;
      default = null;
      description = ''
        TCP port of an EXPLICIT host-side package proxy (e.g. a caching HTTP
        proxy) reachable by guests at <gatewayAddress>:<packageProxyPort>.
        Required by — and only used by — `networkProfile = "package-access"`.
        This module does not start the proxy; it only opens that single port
        for the guest subnet and points the guest's http_proxy/https_proxy at
        it. Deliberately a single host-controlled port rather than general
        egress.
      '';
    };

    dnsServers = mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = ''
        Explicit DNS policy for `networkProfile = "internet"`: the ONLY
        resolvers a guest may reach (port 53, udp+tcp). Every other port-53
        destination stays blocked, so a guest cannot use an arbitrary public
        resolver or a DNS tunnel of its choosing. The guests are also
        configured to use exactly these servers.

        Empty means "the host itself on the bridge" (<gatewayAddress>), which
        requires a resolver listening on the agent bridge. Unused by the other
        profiles (which allow no DNS at all).
      '';
    };

    acknowledgeInsecureNetwork = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Explicit opt-in acknowledging that an INSECURE network profile
        (`package-access` or `internet`) has been deliberately enabled. Without
        it, the secure `proxy-only`/`offline` profiles are the only accepted
        configuration (§37: "private-network / inter-VM / public internet
        without override").
      '';
    };

    passwordlessControl = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Allow the host primary operator (`myconfig.user`, added to a
        dedicated `agent-microvm` group) to drive the `agent-microvm`
        launcher through `sudo` WITHOUT an interactive password prompt.

        This is HOST-OPERATOR CONVENIENCE ONLY and does not weaken the
        untrusted-guest isolation boundary: `agent-microvm` already requires
        root (it mounts virtiofs sources, drives
        `systemctl start/stop microvm@<slot>.service`, chowns clones to the
        guest agent uid/gid and manages runtime state) and is always invoked
        via `sudo`. The hostile guest can never reach host `sudo`; this only
        spares the human operator (who is already a full sudoer) from typing
        their password for each launcher invocation.

        Secure default is false (operator authenticates to sudo as usual).
        When true it grants members of the `agent-microvm` group a scoped
        `NOPASSWD` (plus `SETENV`, so workmux's
        `--preserve-env=AGENT_MICROVM_SSH_KEY` is permitted) rule for exactly
        the `agent-microvm` launcher — nothing broader.
      '';
    };

    hypervisorMemoryOverheadMiB = mkOption {
      type = types.ints.positive;
      default = 1024;
      description = ''
        RAM (MiB) added to a slot's class memory to obtain the HOST-side
        `MemoryMax` of its `microvm@<slot>.service`. The hypervisor process,
        virtiofsd and the guest's page cache all live in that cgroup, so the
        limit must never be below "guest memory + overhead" — otherwise a
        perfectly well-behaved VM gets OOM-killed.
      '';
    };

    hypervisorTasksMax = mkOption {
      type = types.ints.positive;
      default = 512;
      description = ''
        `TasksMax` of a slot's `microvm@<slot>.service` (host side): bounds the
        hypervisor's own threads/processes.
      '';
    };

    hypervisorCPUWeight = mkOption {
      type = types.ints.positive;
      default = 50;
      description = ''
        RELATIVE cgroup CPU weight of a slot's hypervisor unit (systemd default
        is 100). Below 100 on purpose: agent sandboxes should yield to
        interactive host work, while still being allowed to use idle capacity
        (a hard `CPUQuota` would waste it). The per-class `CPUQuota` inside the
        guest is what bounds the agent itself.
      '';
    };

    hypervisorIOWeight = mkOption {
      type = types.ints.positive;
      default = 50;
      description = ''
        RELATIVE cgroup IO weight of a slot's hypervisor unit (systemd default
        is 100), so agent disk traffic yields to interactive host work.
      '';
    };

    taskLogMaxBytes = mkOption {
      type = types.ints.positive;
      default = 1048576;
      description = ''
        Size cap (bytes) of a per-task structured lifecycle log under
        `<runtimeRoot>/logs/<task>.jsonl`. When exceeded, ONE generation is
        rotated to `<task>.jsonl.1`, so batch logs are retained but bounded.
      '';
    };

    guestAgentUid = mkOption {
      type = types.ints.positive;
      default = 1000;
      description = ''
        Numeric uid of the unprivileged guest `agent` user. virtiofsd passes
        ownership through unchanged, so this is ALSO the host-side owner of
        everything the guest must write: the workspace clone, the job output
        directory and any task-scoped agent-state directory.

        Must be unprivileged (never 0). The default 1000 is the primary
        interactive user on a workstation, which is deliberate: the human
        operator can inspect, diff and import the clone directly, and no guest
        id maps to a privileged host id (plan §11).
      '';
    };

    guestAgentGid = mkOption {
      type = types.ints.positive;
      default = 1000;
      description = ''
        Numeric gid used for the host-side ownership of guest-writable paths
        (see `guestAgentUid`). Must be unprivileged (never 0).
      '';
    };

    enableSsh = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Expose an SSH server inside the guest, reachable only on the private
        guest interface. Requires `sshPublicKeyFile` to be set.

        Part of the `interactive` capability, and REJECTED without it: on a host
        whose `capabilities` does not include `"interactive"` there is no SSH
        server, no per-slot host identity and no `known_hosts` database to
        enable, so `enableSsh = true` (the DEFAULT) is an evaluation error there
        rather than a silently ignored value. A `capabilities = [ "batch" ]`
        host must therefore also set `enableSsh = false`.
      '';
    };

    sshPublicKeyFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = ''
        Path to a single dedicated public key authorised for the guest
        `agent` user. Must NOT be a host authorized_keys file. Required when
        `enableSsh` is true.
      '';
    };
  };

  # Phase 0: the only config the module produces is its assertions plus the
  # shared `agentRegistry` module argument, and the assertions apply only when
  # the feature is enabled — so importing the module with the secure defaults
  # (disabled) has no config side effects, forces no agent package (Nix is
  # lazy) and never blocks evaluation. Later phases add the microvm.nix host module, bridge,
  # firewall, slot definitions and Workmux registrations under this same
  # `lib.mkIf cfg.enable`.
  config = lib.mkMerge [
    {
      # Hand the single registry instance to guest.nix / launcher.nix /
      # workmux.nix. Set unconditionally (outside the `mkIf`) because those
      # modules take it as a module argument; Nix laziness means a disabled
      # feature never forces any agent package.
      _module.args.agentRegistry = agentRegistry;
      # Likewise the ONE resolved network decision (profile + capabilities +
      # DNS policy), consumed by network.nix (firewall/NAT) and guest.nix
      # (proxy/DNS/forwarder).
      _module.args.agentNetwork = agentNetwork;
      # The ONE effective resource-class table (`cfg.resourceClasses`, the only
      # spelling there is), so guest.nix / network.nix / launcher.nix /
      # hostkeys.nix / job.nix all build the SAME slot pool.
      _module.args.agentResourceClasses = effectiveResourceClasses;
      # The ONE resolved capability set (lightweight plan phase 5), consumed by
      # session.nix (the layout table), job.nix, hostkeys.nix, guest.nix,
      # launcher.nix and workmux.nix.
      _module.args.agentCapabilities = agentCapabilities;
    }

    (lib.mkIf cfg.enable {
      assertions = [
        {
          # §11: no guest id may map to a privileged host id.
          assertion = cfg.guestAgentUid > 0 && cfg.guestAgentGid > 0;
          message = "myconfig.ai.microvm.guestAgentUid/guestAgentGid must be unprivileged (> 0).";
        }
        {
          assertion = slots != [ ];
          message = "myconfig.ai.microvm: the resource-class pool is empty (no class with count > 0).";
        }
        {
          assertion = lib.length slots <= slotLib.maxSlotCount;
          message = "myconfig.ai.microvm: the total number of slots (${toString (lib.length slots)}) must be <= ${toString slotLib.maxSlotCount} (deterministic MAC/IPv4 generator bound).";
        }
        {
          # Class names end up in slot names, hostnames, interface names and
          # host directories, and cross the host->guest control channel.
          assertion = lib.all (n: builtins.match "[a-z][a-z0-9-]*" n != null) (
            lib.attrNames effectiveResourceClasses
          );
          message = "myconfig.ai.microvm.resourceClasses: class names must match [a-z][a-z0-9-]*.";
        }
        {
          # Linux caps interface names at 15 chars, so a long class name would
          # otherwise fail late, at TAP creation time.
          assertion = lib.all (t: lib.stringLength t <= slotLib.maxInterfaceNameLength) slotTaps;
          message = "myconfig.ai.microvm.resourceClasses: class names are too long — generated TAP names must be <= ${toString slotLib.maxInterfaceNameLength} chars (got ${
            toString (lib.filter (t: lib.stringLength t > slotLib.maxInterfaceNameLength) slotTaps)
          }).";
        }
        {
          assertion = lib.length (lib.unique slotNames) == lib.length slotNames;
          message = "myconfig.ai.microvm: generated slot names are not unique.";
        }
        {
          assertion = lib.length (lib.unique slotTaps) == lib.length slotTaps;
          message = "myconfig.ai.microvm: generated slot TAP names are not unique.";
        }
        {
          assertion = isAbsolutePath cfg.workspaceRoot;
          message = "myconfig.ai.microvm.workspaceRoot must be an absolute path.";
        }
        {
          assertion = isAbsolutePath cfg.runtimeRoot;
          message = "myconfig.ai.microvm.runtimeRoot must be an absolute path.";
        }
        {
          assertion = isAbsolutePath cfg.stateRoot;
          message = "myconfig.ai.microvm.stateRoot must be an absolute path.";
        }
        {
          # `stateRoot` is the host path the launcher and hostkeys.nix use for the
          # VSOCK mux address (`vsock-mux/<stateRoot>/<slot>/notify.vsock`) and
          # for the per-VM bind-mount source. It MUST equal `microvm.stateDir`, the
          # path microvm.nix actually puts per-VM state under (and where
          # cloud-hypervisor backs the VSOCK device with `<stateDir>/<slot>/
          # notify.vsock`). Phase 6 widened the blast radius of this pre-existing
          # assumption — the vsock-mux `known_hosts` entry AND the launcher's ssh
          # target both key on `stateRoot` — so a host that sets one without the
          # other would get a runtime mismatch (the ssh target / known_hosts key
          # would not resolve to the socket microvm created). Fail at EVAL
          # instead. (`stateDir` defaults to `/var/lib/microvms`, the same as
          # `stateRoot`, so every host today satisfies this.) `toString` accounts
          # for `microvm.stateDir` being a `types.path` (a host may set it as a
          # path literal) while `stateRoot` is a `types.str`.
          assertion = cfg.stateRoot == toString config.microvm.stateDir;
          message = ''
            myconfig.ai.microvm.stateRoot ("${cfg.stateRoot}") must equal
            `config.microvm.stateDir` ("${toString config.microvm.stateDir}"): the
            launcher's VSOCK ssh target `vsock-mux/<stateRoot>/<slot>/notify.vsock`
            and the per-slot `known_hosts` entry key on `stateRoot`, while
            microvm.nix backs the VSOCK device under `<stateDir>/<slot>`. Set
            both to the same path.
          '';
        }
        {
          assertion = cfg.bridgeName != "";
          message = "myconfig.ai.microvm.bridgeName must be non-empty.";
        }
        {
          assertion = cfg.gatewayAddress != "";
          message = "myconfig.ai.microvm.gatewayAddress must be non-empty.";
        }
        {
          # An SSH control channel — the `interactive` one (`enableSsh`) OR the
          # `vsock` one (lightweight plan phase 6) — authorises exactly ONE
          # dedicated key on the guest `agent` user, so either requires an
          # explicit `sshPublicKeyFile`. A batch-only host that selects NEITHER
          # needs no key (and has no sshd to authorise one).
          assertion = (!cfg.enableSsh && !agentCapabilities.vsock) || cfg.sshPublicKeyFile != null;
          message = ''
            myconfig.ai.microvm: an SSH control channel (enableSsh = true or the
            `vsock` capability) requires an explicit `sshPublicKeyFile` — the
            guest `agent` user must authorise exactly one dedicated key, never a
            host authorized_keys file.
          '';
        }
        {
          # The VSOCK control channel (lightweight plan phase 6) is the secure
          # profile's control-transport enabler, so the plan restricts it to the
          # closed profiles. Pairing it with `package-access`/`internet` (an
          # INSECURE network profile) is a configuration the plan never
          # intended and is rejected at eval. (`vsock` is ADDITIVE here — the
          # TAP still carries the proxy — so this restriction is the plan's own
          # boundary, not a technical conflict; it is kept because it is the
          # safer, more restrictive choice and matches the plan's phase-9 eval
          # test "VSOCK transport selected with internet access".)
          assertion =
            !agentCapabilities.vsock || effectiveProfile == "proxy-only" || effectiveProfile == "offline";
          message = ''
            myconfig.ai.microvm: the `vsock` capability is only allowed with the
            closed network profiles `proxy-only` or `offline` (this host selects
            `${effectiveProfile}`). VSOCK is the secure profile's control
            transport; pair it with an insecure profile deliberately by NOT
            selecting `vsock` and driving the guest over the TAP instead.
          '';
        }
        {
          # The LITERAL phase-6 transport (`vsock` + `proxy-only`) carries the
          # model API over AF_VSOCK port `litellmPort`, which cloud-hypervisor
          # backs with the Unix socket `<stateRoot>/<slot>/notify.vsock_<port>`.
          # microvm.nix already uses `notify.vsock_8888` for the guest's systemd
          # NOTIFY socket (its socat bridge), so a host that set `litellmPort =
          # 8888` would have the model forwarder and the notify bridge fight over
          # the same socket path — the VM would either fail to signal readiness
          # or lose its model endpoint, both at runtime and both opaque. Reject
          # it at EVAL. Only the vsock transport is affected: under `tap` the
          # port is a plain TCP port on the bridge.
          assertion = !agentNetwork.transportCaps.vsockLitellm || vsockLitellmPort != reservedNotifyVsockPort;
          message = ''
            myconfig.ai.microvm.litellmPort must not be ${toString reservedNotifyVsockPort} on a host
            that uses the VSOCK model transport (the `vsock` capability with
            `networkProfile = "proxy-only"`): the per-VM forwarder listens on the
            cloud-hypervisor VSOCK socket
            `${cfg.stateRoot}/<slot>/notify.vsock_${toString vsockLitellmPort}`, and microvm.nix
            reserves AF_VSOCK port ${toString reservedNotifyVsockPort} (`notify.vsock_${toString reservedNotifyVsockPort}`)
            for the guest's systemd notify socket. Pick a different
            `litellmPort`.
          '';
        }
        {
          # The launcher's VSOCK `ssh` / readiness poll / `status` connect with
          # `ssh vsock-mux/$STATE_ROOT/$slot/notify.vsock`. That hostname only
          # resolves because nixpkgs' `programs.ssh.systemd-ssh-proxy.enable`
          # (default true) includes `20-systemd-ssh-proxy.conf`, which supplies
          # the `Host vsock-mux/*` ProxyCommand (systemd-ssh-proxy -> the guest's
          # vsock::22). A host that sets `programs.ssh.systemd-ssh-proxy.enable =
          # false` AND selects `vsock` would get a confusing runtime
          # DNS-resolution failure of the control channel. Fail at EVAL instead,
          # naming the missing host-side dependency.
          assertion = !agentCapabilities.vsock || config.programs.ssh.systemd-ssh-proxy.enable;
          message = ''
            myconfig.ai.microvm: the `vsock` capability requires
            `programs.ssh.systemd-ssh-proxy.enable = true` (the nixpkgs default).
            The launcher reaches the guest's VSOCK sshd as
            `ssh vsock-mux/<stateRoot>/<slot>/notify.vsock`, a hostname that only
            resolves through the `Host vsock-mux/*` ProxyCommand
            `20-systemd-ssh-proxy.conf` supplies when
            `programs.ssh.systemd-ssh-proxy.enable` is true. With it disabled the
            control channel fails at runtime with an opaque DNS-resolution error.
          '';
        }
        {
          # A typo in `capabilities` must fail at EVAL, naming the token, rather
          # than silently narrowing the guest (a mistyped "interactve" would
          # otherwise produce a batch-only host).
          assertion = unknownCapabilities == [ ];
          message = ''
            myconfig.ai.microvm.capabilities: unknown capability ${
              lib.concatMapStringsSep ", " (c: "'${c}'") unknownCapabilities
            }. Known capabilities are: ${lib.concatStringsSep ", " declaredCapabilities}.
          '';
        }
        {
          # A guest with NEITHER capability can neither be logged into nor be
          # given a job: it would boot, seed a home and idle forever.
          assertion = agentCapabilities.selected != [ ];
          message = ''
            myconfig.ai.microvm.capabilities selects no capability, so the guest
            could neither be entered interactively nor be given a batch job.
            Select at least one of: ${lib.concatStringsSep ", " declaredCapabilities}.
          '';
        }
        {
          # ... and a selection that carries ONLY the TRANSPORT capability is
          # just as empty in practice. `interactive` and `batch` are the two
          # WORKLOAD capabilities (what the guest can be asked to do); `vsock`
          # is a TRANSPORT (how the host reaches it) and declares no workload
          # of its own. `capabilities = [ "vsock" ]` therefore describes a
          # guest that can be reached but has nothing to be reached FOR: it
          # would carry neither the interactive entry point nor the batch job
          # controller, yet the VSOCK sshd would happily hand out a shell — an
          # UNDOCUMENTED third execution mode. Fail CLOSED here rather than
          # inferring a workload from the transport (which would make `vsock`
          # secretly mean `vsock` + `interactive`) or adding a second
          # capability list (which would re-create the cross-product the
          # `full`/`lite` collapse removed).
          assertion = agentCapabilities.interactive || agentCapabilities.batch;
          message = ''
            myconfig.ai.microvm.capabilities selects no WORKLOAD capability
            (currently: ${lib.concatStringsSep ", " agentCapabilities.selected}).
            "interactive" and "batch" are the workload capabilities — what the
            guest can be asked to do; "vsock" is only a TRANSPORT (how the host
            reaches the guest) and cannot be selected alone. Add "interactive",
            "batch", or both.
          '';
        }
        {
          # RECONCILIATION of `enableSsh` vs the capability set (the plan's
          # phase-5 deviation asked for ONE authority): `enableSsh` stays the
          # authoritative switch for the SSH server WITHIN the interactive
          # capability, and it is MEANINGLESS-AND-REJECTED without it. It is
          # deliberately not silently forced to false: the SSH server, the
          # per-slot host identity, the known_hosts database and the launcher's
          # `ssh`/`--attach` paths would all disappear behind an option that
          # still read `true`.
          assertion = !cfg.enableSsh || agentCapabilities.interactive;
          message = ''
            myconfig.ai.microvm.enableSsh = true has no meaning without the
            `interactive` capability: the SSH server, the per-slot SSH host
            identity, the known_hosts database and the launcher's `ssh` /
            `run --attach` paths are all part of that capability. Either add
            "interactive" to `myconfig.ai.microvm.capabilities`
            (currently: ${lib.concatStringsSep ", " agentCapabilities.selected}) or set
            `myconfig.ai.microvm.enableSsh = false`.
          '';
        }
        {
          # The secure default must stay the default: widening the guest's
          # reach beyond the model API needs an explicit acknowledgement.
          assertion =
            !(builtins.elem effectiveProfile profileLib.insecureProfiles) || cfg.acknowledgeInsecureNetwork;
          message = ''
            myconfig.ai.microvm: networkProfile = "${effectiveProfile}" is an
            INSECURE profile (it widens the guest's reach beyond the host
            LiteLLM endpoint). To use it deliberately, also set
            `myconfig.ai.microvm.acknowledgeInsecureNetwork = true`.
          '';
        }
        {
          assertion = effectiveProfile != "package-access" || cfg.packageProxyPort != null;
          message = ''
            myconfig.ai.microvm: networkProfile = "package-access" requires
            `packageProxyPort` (the host proxy port guests are allowed to
            reach). Without it the profile would grant nothing beyond
            proxy-only.
          '';
        }
        {
          assertion = cfg.packageProxyPort == null || cfg.packageProxyPort != cfg.litellmPort;
          message = "myconfig.ai.microvm.packageProxyPort must differ from litellmPort.";
        }
        {
          # The guest-side forwarder and the host-side socket both point the
          # model API at the loopback LiteLLM proxy on
          # 127.0.0.1:<litellmPort>, and every guest agent config assumes that
          # endpoint exists. A host that enables a litellm-capable profile
          # (`proxy-only` / `package-access` / `internet`) WITHOUT
          # `services.litellm.enable` produces a sandbox whose guest can reach
          # the bridge endpoint but finds nothing behind it — so every batch
          # job dies a few seconds in with no actionable message. Fail this at
          # EVAL instead, naming the missing backend. (`offline` needs no
          # backend: its guests get no litellm capability.)
          assertion = !agentNetwork.caps.litellm || (config.services.litellm.enable or false);
          message = ''
            myconfig.ai.microvm: the effective network profile
            `${effectiveProfile}` lets guests reach the model API, but
            `services.litellm.enable` is false (or the litellm module is not
            imported). The guest-side loopback forwarder hands connections to
            `127.0.0.1:${toString cfg.litellmPort}`, which only exists when the
            host LiteLLM proxy is enabled — without it every agent batch job
            dies within seconds. Either enable `services.litellm` on this host
            or switch the microVM profile to `offline`.
          '';
        }
        {
          assertion = lib.length (lib.unique slotIPs) == lib.length slotIPs;
          message = "myconfig.ai.microvm: generated slot IPv4 addresses are not unique.";
        }
        {
          assertion = lib.length (lib.unique slotMACs) == lib.length slotMACs;
          message = "myconfig.ai.microvm: generated slot MAC addresses are not unique.";
        }
        {
          assertion = lib.length (lib.unique slotCIDs) == lib.length slotCIDs;
          message = "myconfig.ai.microvm: generated slot VSOCK CIDs are not unique.";
        }
        {
          # 0 (hypervisor), 1 (loopback) and 2 (host) are reserved VSOCK CIDs;
          # 0xffffffff is VMADDR_CID_ANY.
          assertion = lib.all (c: c > 2 && c < 4294967295) slotCIDs;
          message = "myconfig.ai.microvm: generated slot VSOCK CIDs must avoid the reserved values 0/1/2 and VMADDR_CID_ANY.";
        }
        {
          assertion = effectiveRegistry.declaredNames != [ ];
          message = "myconfig.ai.microvm: the agent registry (agents.nix) must declare at least one agent.";
        }
        {
          # A typo in `enabledAgents` must fail loudly at EVAL instead of
          # silently producing a guest with fewer (or no) agents.
          assertion = effectiveRegistry.unknownEnabled == [ ];
          message = ''
            myconfig.ai.microvm.enabledAgents: unknown agent(s) ${lib.concatStringsSep ", " effectiveRegistry.unknownEnabled}.
            Declared agents are: ${lib.concatStringsSep ", " effectiveRegistry.declaredNames}.
          '';
        }
        {
          # An empty selection would build a guest that can run nothing at all.
          assertion = effectiveRegistry.names != [ ];
          message = ''
            myconfig.ai.microvm.enabledAgents selects no agent, so the guest
            would contain no agent runtime at all. Select at least one of:
            ${lib.concatStringsSep ", " effectiveRegistry.declaredNames}.
          '';
        }
        {
          # The BATCH machinery (host `submit` validation, guest controller and
          # worker dispatch) renders `case` PATTERNS from the batch-capable
          # subset; an empty subset renders an empty pattern, i.e. a
          # syntactically broken script. CONDITIONAL on the `batch` capability
          # (lightweight plan phase 5): a host that does not select `batch`
          # builds none of that machinery, so an interactive-only
          # `enabledAgents` selection is legitimate there — which is the whole
          # point of the phase.
          assertion = !agentCapabilities.batch || effectiveRegistry.batchNames != [ ];
          message = ''
            myconfig.ai.microvm.enabledAgents selects no agent that can run
            UNATTENDED (no `batchArgs` in ./agents.nix), but this host selects
            the `batch` capability, so its guests carry the batch job
            machinery. Either include at least one batch-capable agent
            (${lib.concatStringsSep ", " effectiveRegistry.declaredBatchNames}) or drop
            "batch" from `myconfig.ai.microvm.capabilities`.
          '';
        }
      ]
      # One assertion per malformed registry entry (empty when well-formed).
      ++ map (msg: {
        assertion = false;
        message = msg;
      }) effectiveRegistry.errors;

    })
  ];
}
