# Copyright 2025 Maximilian Huber <oss@maximilian-huber.de>
# SPDX-License-Identifier: MIT
#
# myconfig.ai.microvm — Cloud Hypervisor agent-sandbox tier.
#
# A second, stronger isolation tier for autonomous coding agents, alongside
# the existing QEMU/SLiRP `flake.sandboxed-pi.nix` tier. It runs each agent
# session inside a Cloud Hypervisor microVM (via the `microvm.nix` flake
# input) with its own kernel, a disposable root/home, a single writable
# virtiofs `/workspace` mount (a standalone git clone), a dedicated private
# bridge, and model-API access restricted to the host LiteLLM proxy through a
# bridge-only forwarding endpoint. Every agent process and guest workload is
# treated as potentially hostile; the secure default prioritises isolation
# over convenience.
#
# PHASE 0 — this file only *defines the option namespace, assertions and
# registration*. It also instantiates the authoritative supported-agent
# registry (./agents.nix) EXACTLY ONCE and passes it to the sibling modules as
# `_module.args.agentRegistry`. The feature is disabled by default and, while
# disabled,
# produces no config side effects: it does NOT import the microvm.nix host
# module, create the bridge/firewall rules, define VM slots, build the guest,
# or register Workmux agents. Those are implemented in later phases inside
# guest.nix / network.nix / launcher.nix / workmux.nix. The option reference
# lives in `./docs/agent-microvm.md`.
{
  config,
  # `options` is used to detect whether a DEPRECATED legacy network boolean was
  # explicitly defined by a host, so the migration can warn / translate / reject
  # instead of silently ignoring it (ticket 3 C).
  options,
  lib,
  pkgs,
  inputs,
  ...
}:
let
  cfg = config.myconfig.ai.microvm;

  # --- deterministic fixed slot pool (agent-0 .. agent-<slotCount-1>) -----
  # The slot table is generated by the shared helper in slots.nix — the same
  # helper guest.nix uses to actually build the VMs — so these uniqueness /
  # bound assertions (§37) always guard the exact table that builds the VMs.
  slotLib = import ./slots.nix { inherit lib; };
  slots = slotLib.mkSlots effectiveResourceClasses;
  slotIPs = map (s: s.ip) slots;
  slotMACs = map (s: s.mac) slots;
  slotCIDs = map (s: s.cid) slots;
  slotNames = map (s: s.name) slots;
  slotTaps = map (s: s.tap) slots;

  # --- ticket 5 A: fixed resource classes + legacy-option migration --------
  # The pool is grouped into PREBUILT classes; `slotCount` / `defaultVcpu` /
  # `defaultMemoryMiB` are the deprecated single-class spelling of the same
  # thing. Exactly like the ticket-3 network booleans, "explicitly defined" is
  # decided by option PRIORITY (see `isExplicit`), never by `isDefined`.
  legacySlotOpts = {
    slotCount = options.myconfig.ai.microvm.slotCount;
    defaultVcpu = options.myconfig.ai.microvm.defaultVcpu;
    defaultMemoryMiB = options.myconfig.ai.microvm.defaultMemoryMiB;
  };
  definedLegacySlotOpts = lib.attrNames (lib.filterAttrs (_: isExplicit) legacySlotOpts);
  classesExplicit = isExplicit options.myconfig.ai.microvm.resourceClasses;

  # A host that sets BOTH spellings would silently lose one of them, so that is
  # rejected (assertion below) instead of resolved.
  slotOptsAmbiguous = classesExplicit && definedLegacySlotOpts != [ ];

  # --- lightweight plan phase 1: the profile table ------------------------
  # `profile` is the compatibility boundary between the existing full-featured
  # tier (`full`, the default, byte-for-byte unchanged) and the lightweight one
  # (`lite`). ./profiles.nix is the authoritative table; the resolved entry is
  # handed to guest.nix through `_module.args.agentProfile` so there is ONE
  # decision site.
  profilesLib = import ./profiles.nix { inherit lib; };
  agentProfile = profilesLib.forProfile cfg.profile // {
    name = cfg.profile;
  };

  # A profile that carries its own class table only applies when the host said
  # nothing about sizing at all — an explicit `resourceClasses` always wins
  # ("explicit user options higher priority than profile defaults"). Combining
  # it with the DEPRECATED slot options is rejected rather than resolved (see
  # the assertion below), so exactly one of the three branches can apply.
  profileResourceClasses = agentProfile.resourceClasses;
  # Only relevant when the profile table would actually be USED: with an
  # explicit `resourceClasses` the profile's table is ignored anyway and
  # `slotOptsAmbiguous` is the assertion that fires.
  profileSlotOptsAmbiguous =
    profileResourceClasses != null && !classesExplicit && definedLegacySlotOpts != [ ];

  # Without an explicit `resourceClasses`, synthesize the single `normal` class
  # the legacy options describe — so the pool (and every slot's identity) is
  # exactly what those options meant, just named `agent-normal-<i>`.
  legacyResourceClasses = {
    normal = {
      count = cfg.slotCount;
      vcpu = cfg.defaultVcpu;
      memoryMiB = cfg.defaultMemoryMiB;
    };
  };
  effectiveResourceClasses =
    if classesExplicit then
      cfg.resourceClasses
    else if profileResourceClasses != null then
      profileResourceClasses
    else
      legacyResourceClasses;

  # "Explicitly defined" means a definition with a HIGHER priority than the
  # option default. `isDefined` cannot be used: nixpkgs implements
  # `mkOption { default = ...; }` as a low-priority (1500) definition, so every
  # option with a default is always "defined". `lib.mkOptionDefault`'s priority
  # (1500) is exactly that boundary — `mkDefault` (1000) and a plain
  # host-level definition (100) both rank above it (lower number == stronger).
  optionDefaultPriority = 1500;
  isExplicit = opt: opt.highestPrio < optionDefaultPriority;

  # --- authoritative supported-agent registry -----------------------------
  # ./agents.nix is the SINGLE SOURCE OF TRUTH for the supported agents (guest
  # packages + guest env, guest `agent-run` dispatch, launcher validation +
  # help, workmux registrations). Instantiated EXACTLY ONCE here and handed to
  # the sibling modules through `_module.args.agentRegistry`, so every
  # consumer sees the same registry with the same context (endpoint, model)
  # and cannot re-instantiate it with different arguments.
  #
  # Its well-formedness errors are surfaced as NixOS assertions below, so a
  # malformed entry fails loudly here instead of producing a broken guest
  # closure or a launcher that accepts an agent the guest cannot run.

  # Which of the declared agents this host actually builds into its guests
  # (lightweight plan phase 2). Resolved ONCE, here, from the explicit option
  # and the profile's own default; `null` keeps every declared agent, which is
  # the historical behaviour and the `full` profile's default.
  effectiveEnabledAgents =
    if cfg.enabledAgents != null then cfg.enabledAgents else agentProfile.enabledAgents;

  agentRegistry = import ./agents.nix {
    inherit lib pkgs inputs;
    enabledNames = effectiveEnabledAgents;
    litellmPort = cfg.litellmPort;
    # Hermes cannot discover a model on its own; reuse the model name the host
    # `myconfig.ai.hermes` backends use (a LiteLLM route). Reading the option
    # (not `cfg`) keeps ONE model definition for host and sandbox alike.
    hermesModel = config.myconfig.ai.hermes.model.default;
  };

  # --- ticket 3 C: network profiles + legacy-boolean migration ------------
  # `network-profiles.nix` is the authoritative capability table; the effective
  # profile is resolved HERE (the only place that can see whether a host
  # explicitly defined an option) and handed to network.nix / guest.nix through
  # `_module.args.agentNetwork`, so host firewall policy and guest-side proxy /
  # DNS configuration are derived from ONE decision.
  profileLib = import ./network-profiles.nix { inherit lib; };

  legacyOpts = {
    allowPublicInternet = options.myconfig.ai.microvm.allowPublicInternet;
    allowInterVmTraffic = options.myconfig.ai.microvm.allowInterVmTraffic;
    allowPrivateNetworks = options.myconfig.ai.microvm.allowPrivateNetworks;
  };
  definedLegacyOpts = lib.attrNames (lib.filterAttrs (_: isExplicit) legacyOpts);
  profileExplicit = isExplicit options.myconfig.ai.microvm.networkProfile;

  # Translate the ONE legacy boolean that has an exact profile equivalent.
  # `allowPrivateNetworks` / `allowInterVmTraffic` have none and are rejected
  # by the assertions below (never silently downgraded to something laxer OR
  # silently ignored).
  legacyWantsInternet = cfg.allowPublicInternet;
  legacyAmbiguous = legacyWantsInternet && profileExplicit && cfg.networkProfile != "internet";
  effectiveProfile =
    if profileExplicit then
      cfg.networkProfile
    else if legacyWantsInternet then
      "internet"
    else
      cfg.networkProfile;

  agentNetwork = {
    profile = effectiveProfile;
    caps = profileLib.forProfile effectiveProfile;
    # Effective DNS policy for the `internet` profile: an empty `dnsServers`
    # means "the host itself on the bridge".
    dnsServers = if cfg.dnsServers == [ ] then [ cfg.gatewayAddress ] else cfg.dnsServers;
  };

  isAbsolutePath = p: lib.hasPrefix "/" p;
in
{
  imports = [
    ./config-seed.nix
    ./guest.nix
    ./guest-home.nix
    ./guest-model-config.nix
    ./hostkeys.nix
    ./job.nix
    ./state.nix
    ./network.nix
    ./launcher.nix
    ./secrets.nix
    ./workmux.nix
  ];

  options.myconfig.ai.microvm = with lib; {
    enable = mkEnableOption "myconfig.ai.microvm (Cloud Hypervisor agent sandboxes)";

    profile = mkOption {
      type = types.enum profilesLib.names;
      default = "full";
      description = ''
        Named overall SHAPE of the sandbox tier (see ./profiles.nix for the
        authoritative table and
        ./docs/myconfig-ai-microvm-lightweight-plan.md for the rationale).

        - `full` the existing, full-featured behaviour and the default: sizing
                 comes from `resourceClasses` (or the deprecated slot options)
                 and the guest store disk keeps microvm.nix's own defaults.
        - `lite` the LIGHTWEIGHT shape: ONE prebuilt slot with 2 vCPU and
                 4 GiB RAM, and an explicitly pinned, optimized EROFS guest
                 store (`microvm.optimize.enable`, `microvm.storeDiskType`).

        The profile only supplies DEFAULTS: an explicit `resourceClasses`
        always outranks the profile's class table. Combining `lite` with the
        deprecated `slotCount` / `defaultVcpu` / `defaultMemoryMiB` spelling is
        rejected as ambiguous instead of silently resolved.
      '';
    };

    enabledAgents = mkOption {
      type = types.nullOr (types.listOf types.str);
      default = null;
      example = literalExpression ''[ "codex" ]'';
      description = ''
        SELECTED coding agents (tokens of the authoritative registry in
        ./agents.nix). Everything agent-shaped is derived from this selection:
        the guest closure's agent packages and per-agent guest environment, the
        guest `agent-run` dispatch, the batch worker's dispatch, the host
        launcher's `--agent` validation and help text, the Workmux
        `microvm-*` registrations and the agent-state directories. A
        deselected agent is therefore ABSENT from the guest image, not merely
        hidden, and `--agent <name>` for it is rejected.

        `null` (the default) means "whatever the `profile` selects", which for
        `profile = "full"` is EVERY declared agent — i.e. the historical
        behaviour. An unknown token is rejected at evaluation time.
      '';
    };

    resourceClasses = mkOption {
      type = types.attrsOf (
        types.submodule {
          options = {
            count = mkOption {
              type = types.ints.positive;
              description = "Number of PREBUILT slots in this class.";
            };
            vcpu = mkOption {
              type = types.ints.positive;
              description = "vCPUs per guest in this class.";
            };
            memoryMiB = mkOption {
              type = types.ints.positive;
              description = "Guest RAM per guest in this class, in MiB.";
            };
          };
        }
      );
      default = {
        normal = {
          count = 4;
          vcpu = 4;
          memoryMiB = 8192;
        };
      };
      defaultText = literalExpression ''
        { normal = { count = slotCount; vcpu = defaultVcpu; memoryMiB = defaultMemoryMiB; }; }
      '';
      example = literalExpression ''
        {
          small  = { count = 2; vcpu = 2; memoryMiB = 4096; };
          normal = { count = 4; vcpu = 4; memoryMiB = 8192; };
          large  = { count = 1; vcpu = 8; memoryMiB = 16384; };
        }
      '';
      description = ''
        Fixed, PREBUILT resource classes. Each class contributes `count` slots
        named `agent-<class>-<i>` with the class's `vcpu` / `memoryMiB` sizing;
        every slot keeps its own deterministic TAP, MAC, IPv4, VSOCK CID, state
        directory, job directory and (with `enableSsh`) SSH host identity.

        There is deliberately NO per-job Nix evaluation: `submit`/`run` allocate
        from this fixed pool with `--resource-class <name>`, and the allocator
        only ever considers the requested class (it never silently substitutes
        a smaller one).

        NOTE (merge semantics): defining a single class, e.g.
        `resourceClasses.large = { … }`, MERGES with the default `normal` class
        rather than replacing it. Use `lib.mkForce { … }` to define the pool
        exhaustively.

        When this option is not set explicitly, it is derived from the
        deprecated `slotCount` / `defaultVcpu` / `defaultMemoryMiB` options, so
        an existing configuration keeps exactly its previous sizing (as a single
        `normal` class).
      '';
    };

    slotCount = mkOption {
      type = types.ints.positive;
      default = 4;
      description = ''
        DEPRECATED (ticket 5) — use `resourceClasses`.

        Number of fixed, declaratively defined microVM slots. Still honoured
        when `resourceClasses` is not set explicitly: the pool then consists of
        one `normal` class with this many slots. Setting BOTH spellings is
        rejected as ambiguous.
      '';
    };

    defaultVcpu = mkOption {
      type = types.ints.positive;
      default = 4;
      description = ''
        DEPRECATED (ticket 5) — use `resourceClasses.<name>.vcpu`. vCPUs of the
        single `normal` class synthesized from the legacy options.
      '';
    };

    defaultMemoryMiB = mkOption {
      type = types.ints.positive;
      default = 8192;
      description = ''
        DEPRECATED (ticket 5) — use `resourceClasses.<name>.memoryMiB`. Guest
        RAM (MiB) of the single `normal` class synthesized from the legacy
        options.
      '';
    };

    bridgeName = mkOption {
      type = types.str;
      default = "agentbr0";
      description = "Name of the dedicated private bridge for agent microVMs.";
    };

    subnet = mkOption {
      type = types.str;
      default = "192.168.83.0/24";
      description = "IPv4 subnet (CIDR) of the private agent bridge.";
    };

    gatewayAddress = mkOption {
      type = types.str;
      default = "192.168.83.1";
      description = ''
        Host-side IPv4 address on the agent bridge. Also the address on
        which the bridge-only LiteLLM forwarding endpoint listens.
      '';
    };

    litellmPort = mkOption {
      type = types.port;
      default = 4000;
      description = ''
        TCP port of the host LiteLLM proxy. The guest reaches the model API
        only via <gatewayAddress>:<litellmPort>, forwarded to the
        loopback-only LiteLLM proxy on 127.0.0.1:<litellmPort>.
      '';
    };

    workspaceRoot = mkOption {
      type = types.str;
      default = "/var/lib/agent-microvms/workspaces";
      description = ''
        Absolute host path under which per-task standalone git clones are
        created. Exactly one clone is mounted read-write into a slot at
        /workspace.
      '';
    };

    runtimeRoot = mkOption {
      type = types.str;
      default = "/var/lib/agent-microvms";
      description = ''
        Absolute host path for agent-microvm runtime state (task metadata,
        locks, bind-mount sources). Must be an absolute path.
      '';
    };

    stateRoot = mkOption {
      type = types.str;
      default = "/var/lib/microvms";
      description = ''
        Absolute host path used by microvm.nix for per-VM state
        (/var/lib/microvms/<slot>).
      '';
    };

    networkProfile = mkOption {
      type = types.enum profileLib.names;
      default = "proxy-only";
      description = ''
        Named, coherent guest network policy. Replaces the ambiguous
        allowPublicInternet / allowPrivateNetworks / allowInterVmTraffic
        booleans (which are deprecated, see their descriptions).

        - `offline`        only the control traffic required to manage the VM
                          (host -> guest SSH/console). No model API, no DNS,
                          no package proxy, no routing.
        - `proxy-only`     THE SECURE DEFAULT: additionally the bridge-only
                          LiteLLM endpoint <gatewayAddress>:<litellmPort>, and
                          nothing else.
        - `package-access` additionally ONE explicit host package-proxy port
                          (`packageProxyPort`), with http_proxy/https_proxy
                          pointed at it. Still no routing, NAT or DNS, so it
                          is NOT unrestricted internet.
        - `internet`       full functional egress: routing, NAT/masquerading,
                          an explicit DNS policy (`dnsServers`) and
                          rate-limited drop logging. INSECURE.

        In EVERY profile: guest-to-guest traffic is blocked (per-TAP L2
        `isolated` + IPv4 FORWARD DROP), and the cloud-metadata IP plus all
        private/special-use IPv4 ranges (host LAN, VPN peers, RFC1918, CGNAT,
        loopback, link-local, multicast, reserved) are dropped.

        `package-access` and `internet` require
        `acknowledgeInsecureNetwork = true`.

        See ./network-profiles.nix for the authoritative capability table.
      '';
    };

    packageProxyPort = mkOption {
      type = types.nullOr types.port;
      default = null;
      description = ''
        TCP port of an EXPLICIT host-side package proxy (e.g. a caching HTTP
        proxy) reachable by guests at <gatewayAddress>:<packageProxyPort>.
        Required by — and only used by — `networkProfile = "package-access"`.
        This module does not start the proxy; it only opens that single port
        for the guest subnet and points the guest's http_proxy/https_proxy at
        it. Deliberately a single host-controlled port rather than general
        egress.
      '';
    };

    dnsServers = mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = ''
        Explicit DNS policy for `networkProfile = "internet"`: the ONLY
        resolvers a guest may reach (port 53, udp+tcp). Every other port-53
        destination stays blocked, so a guest cannot use an arbitrary public
        resolver or a DNS tunnel of its choosing. The guests are also
        configured to use exactly these servers.

        Empty means "the host itself on the bridge" (<gatewayAddress>), which
        requires a resolver listening on the agent bridge. Unused by the other
        profiles (which allow no DNS at all).
      '';
    };

    allowPublicInternet = mkOption {
      type = types.bool;
      default = false;
      description = ''
        DEPRECATED (ticket 3 C) — use `networkProfile = "internet"`.

        Still honoured for migration: when set to true and `networkProfile` is
        not explicitly set, the effective profile becomes `internet` and a
        warning is emitted. Setting it together with a DIFFERENT explicit
        `networkProfile` is rejected as ambiguous rather than silently
        resolved.
      '';
    };

    allowInterVmTraffic = mkOption {
      type = types.bool;
      default = false;
      description = ''
        REMOVED (ticket 3 A/C) — guest-to-guest isolation is now
        unconditional: every guest TAP is an `isolated` bridge port, which
        blocks guest<->guest frames for every EtherType before netfilter even
        runs. There is no supported way to relax it, so setting this to true
        is REJECTED with an assertion instead of silently having no effect.
      '';
    };

    allowPrivateNetworks = mkOption {
      type = types.bool;
      default = false;
      description = ''
        REMOVED (ticket 3 C) — no profile grants access to private IPv4 ranges
        (host LAN, VPN peers, RFC1918, CGNAT, link-local, metadata). Setting
        this to true is REJECTED with an assertion rather than silently
        ignored; if a guest genuinely needs to fetch packages, use
        `networkProfile = "package-access"` with an explicit host proxy.
      '';
    };

    acknowledgeInsecureNetwork = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Explicit opt-in acknowledging that an INSECURE network profile
        (`package-access` or `internet`) — or the deprecated
        `allowPublicInternet` boolean — has been deliberately enabled. Without
        it, the secure `proxy-only`/`offline` profiles are the only accepted
        configuration (§37: "private-network / inter-VM / public internet
        without override").
      '';
    };

    passwordlessControl = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Allow the host primary operator (`myconfig.user`, added to a
        dedicated `agent-microvm` group) to drive the `agent-microvm`
        launcher through `sudo` WITHOUT an interactive password prompt.

        This is HOST-OPERATOR CONVENIENCE ONLY and does not weaken the
        untrusted-guest isolation boundary: `agent-microvm` already requires
        root (it mounts virtiofs sources, drives
        `systemctl start/stop microvm@<slot>.service`, chowns clones to the
        guest agent uid/gid and manages runtime state) and is always invoked
        via `sudo`. The hostile guest can never reach host `sudo`; this only
        spares the human operator (who is already a full sudoer) from typing
        their password for each launcher invocation.

        Secure default is false (operator authenticates to sudo as usual).
        When true it grants members of the `agent-microvm` group a scoped
        `NOPASSWD` (plus `SETENV`, so workmux's
        `--preserve-env=AGENT_MICROVM_SSH_KEY` is permitted) rule for exactly
        the `agent-microvm` launcher — nothing broader.
      '';
    };

    hypervisorMemoryOverheadMiB = mkOption {
      type = types.ints.positive;
      default = 1024;
      description = ''
        RAM (MiB) added to a slot's class memory to obtain the HOST-side
        `MemoryMax` of its `microvm@<slot>.service`. The hypervisor process,
        virtiofsd and the guest's page cache all live in that cgroup, so the
        limit must never be below "guest memory + overhead" — otherwise a
        perfectly well-behaved VM gets OOM-killed.
      '';
    };

    hypervisorTasksMax = mkOption {
      type = types.ints.positive;
      default = 512;
      description = ''
        `TasksMax` of a slot's `microvm@<slot>.service` (host side): bounds the
        hypervisor's own threads/processes.
      '';
    };

    hypervisorCPUWeight = mkOption {
      type = types.ints.positive;
      default = 50;
      description = ''
        RELATIVE cgroup CPU weight of a slot's hypervisor unit (systemd default
        is 100). Below 100 on purpose: agent sandboxes should yield to
        interactive host work, while still being allowed to use idle capacity
        (a hard `CPUQuota` would waste it). The per-class `CPUQuota` inside the
        guest is what bounds the agent itself.
      '';
    };

    hypervisorIOWeight = mkOption {
      type = types.ints.positive;
      default = 50;
      description = ''
        RELATIVE cgroup IO weight of a slot's hypervisor unit (systemd default
        is 100), so agent disk traffic yields to interactive host work.
      '';
    };

    taskLogMaxBytes = mkOption {
      type = types.ints.positive;
      default = 1048576;
      description = ''
        Size cap (bytes) of a per-task structured lifecycle log under
        `<runtimeRoot>/logs/<task>.jsonl`. When exceeded, ONE generation is
        rotated to `<task>.jsonl.1`, so batch logs are retained but bounded.
      '';
    };

    guestAgentUid = mkOption {
      type = types.ints.positive;
      default = 1000;
      description = ''
        Numeric uid of the unprivileged guest `agent` user. virtiofsd passes
        ownership through unchanged, so this is ALSO the host-side owner of
        everything the guest must write: the workspace clone, the job output
        directory and any task-scoped agent-state directory.

        Must be unprivileged (never 0). The default 1000 is the primary
        interactive user on a workstation, which is deliberate: the human
        operator can inspect, diff and import the clone directly, and no guest
        id maps to a privileged host id (plan §11).
      '';
    };

    guestAgentGid = mkOption {
      type = types.ints.positive;
      default = 1000;
      description = ''
        Numeric gid used for the host-side ownership of guest-writable paths
        (see `guestAgentUid`). Must be unprivileged (never 0).
      '';
    };

    enableSsh = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Expose an SSH server inside the guest, reachable only on the private
        guest interface. Requires `sshPublicKeyFile` to be set.
      '';
    };

    sshPublicKeyFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = ''
        Path to a single dedicated public key authorised for the guest
        `agent` user. Must NOT be a host authorized_keys file. Required when
        `enableSsh` is true.
      '';
    };
  };

  # Phase 0: the only config the module produces is its assertions plus the
  # shared `agentRegistry` module argument, and the assertions apply only when
  # the feature is enabled — so importing the module with the secure defaults
  # (disabled) has no config side effects, forces no agent package (Nix is
  # lazy) and never blocks evaluation. Later phases add the microvm.nix host module, bridge,
  # firewall, slot definitions and Workmux registrations under this same
  # `lib.mkIf cfg.enable`.
  config = lib.mkMerge [
    {
      # Hand the single registry instance to guest.nix / launcher.nix /
      # workmux.nix. Set unconditionally (outside the `mkIf`) because those
      # modules take it as a module argument; Nix laziness means a disabled
      # feature never forces any agent package.
      _module.args.agentRegistry = agentRegistry;
      # Likewise the ONE resolved network decision (profile + capabilities +
      # DNS policy), consumed by network.nix (firewall/NAT) and guest.nix
      # (proxy/DNS/forwarder).
      _module.args.agentNetwork = agentNetwork;
      # The ONE resolved profile entry (./profiles.nix), consumed by guest.nix
      # for the pinned store-disk / optimization settings.
      _module.args.agentProfile = agentProfile;
      # The ONE effective resource-class table, so guest.nix / network.nix /
      # launcher.nix / hostkeys.nix / job.nix all build the SAME slot pool
      # (including the legacy-option migration above).
      _module.args.agentResourceClasses = effectiveResourceClasses;
    }

    (lib.mkIf cfg.enable {
      assertions = [
        {
          # §11: no guest id may map to a privileged host id.
          assertion = cfg.guestAgentUid > 0 && cfg.guestAgentGid > 0;
          message = "myconfig.ai.microvm.guestAgentUid/guestAgentGid must be unprivileged (> 0).";
        }
        {
          assertion = slots != [ ];
          message = "myconfig.ai.microvm: the resource-class pool is empty (no class with count > 0).";
        }
        {
          assertion = lib.length slots <= slotLib.maxSlotCount;
          message = "myconfig.ai.microvm: the total number of slots (${toString (lib.length slots)}) must be <= ${toString slotLib.maxSlotCount} (deterministic MAC/IPv4 generator bound).";
        }
        {
          # Class names end up in slot names, hostnames, interface names and
          # host directories, and cross the host->guest control channel.
          assertion = lib.all (n: builtins.match "[a-z][a-z0-9-]*" n != null) (
            lib.attrNames effectiveResourceClasses
          );
          message = "myconfig.ai.microvm.resourceClasses: class names must match [a-z][a-z0-9-]*.";
        }
        {
          # Linux caps interface names at 15 chars, so a long class name would
          # otherwise fail late, at TAP creation time.
          assertion = lib.all (t: lib.stringLength t <= slotLib.maxInterfaceNameLength) slotTaps;
          message = "myconfig.ai.microvm.resourceClasses: class names are too long — generated TAP names must be <= ${toString slotLib.maxInterfaceNameLength} chars (got ${
            toString (lib.filter (t: lib.stringLength t > slotLib.maxInterfaceNameLength) slotTaps)
          }).";
        }
        {
          assertion = lib.length (lib.unique slotNames) == lib.length slotNames;
          message = "myconfig.ai.microvm: generated slot names are not unique.";
        }
        {
          assertion = lib.length (lib.unique slotTaps) == lib.length slotTaps;
          message = "myconfig.ai.microvm: generated slot TAP names are not unique.";
        }
        {
          assertion = !profileSlotOptsAmbiguous;
          message = ''
            myconfig.ai.microvm: ambiguous slot configuration — `profile =
            "${cfg.profile}"` carries its own resource-class table AND the
            deprecated ${lib.concatStringsSep " / " definedLegacySlotOpts} ${
              if lib.length definedLegacySlotOpts == 1 then "is" else "are"
            } also set. Keep only `resourceClasses` (or switch to
            `profile = "full"`).
          '';
        }
        {
          assertion = !slotOptsAmbiguous;
          message = ''
            myconfig.ai.microvm: ambiguous slot configuration — `resourceClasses`
            is set explicitly AND the deprecated ${lib.concatStringsSep " / " definedLegacySlotOpts} ${
              if lib.length definedLegacySlotOpts == 1 then "is" else "are"
            } also
            set. Keep only `resourceClasses`.
          '';
        }
        {
          assertion = isAbsolutePath cfg.workspaceRoot;
          message = "myconfig.ai.microvm.workspaceRoot must be an absolute path.";
        }
        {
          assertion = isAbsolutePath cfg.runtimeRoot;
          message = "myconfig.ai.microvm.runtimeRoot must be an absolute path.";
        }
        {
          assertion = isAbsolutePath cfg.stateRoot;
          message = "myconfig.ai.microvm.stateRoot must be an absolute path.";
        }
        {
          assertion = cfg.bridgeName != "";
          message = "myconfig.ai.microvm.bridgeName must be non-empty.";
        }
        {
          assertion = cfg.gatewayAddress != "";
          message = "myconfig.ai.microvm.gatewayAddress must be non-empty.";
        }
        {
          assertion = !cfg.enableSsh || cfg.sshPublicKeyFile != null;
          message = "myconfig.ai.microvm.enableSsh requires an explicit sshPublicKeyFile.";
        }
        {
          # The secure default must stay the default: widening the guest's
          # reach beyond the model API needs an explicit acknowledgement.
          assertion =
            !(builtins.elem effectiveProfile profileLib.insecureProfiles) || cfg.acknowledgeInsecureNetwork;
          message = ''
            myconfig.ai.microvm: networkProfile = "${effectiveProfile}" is an
            INSECURE profile (it widens the guest's reach beyond the host
            LiteLLM endpoint). To use it deliberately, also set
            `myconfig.ai.microvm.acknowledgeInsecureNetwork = true`.
          '';
        }
        {
          # Migration: never resolve a contradiction silently.
          assertion = !legacyAmbiguous;
          message = ''
            myconfig.ai.microvm: ambiguous network configuration — the
            deprecated `allowPublicInternet = true` asks for the `internet`
            profile, but `networkProfile` is explicitly set to
            "${cfg.networkProfile}". Remove `allowPublicInternet` and keep only
            `networkProfile`.
          '';
        }
        {
          assertion = !cfg.allowInterVmTraffic;
          message = ''
            myconfig.ai.microvm: `allowInterVmTraffic` has been REMOVED.
            Guest-to-guest isolation is now unconditional (every guest TAP is
            an `isolated` bridge port, which blocks guest<->guest frames for
            every EtherType). Keeping the option true would be a lie, so it is
            rejected — drop it from your configuration.
          '';
        }
        {
          assertion = !cfg.allowPrivateNetworks;
          message = ''
            myconfig.ai.microvm: `allowPrivateNetworks` has been REMOVED. No
            network profile grants guests access to private IPv4 ranges (host
            LAN, VPN peers, RFC1918, CGNAT, link-local, cloud metadata). If a
            guest needs to fetch packages, use
            `networkProfile = "package-access"` together with an explicit host
            proxy (`packageProxyPort`).
          '';
        }
        {
          assertion = effectiveProfile != "package-access" || cfg.packageProxyPort != null;
          message = ''
            myconfig.ai.microvm: networkProfile = "package-access" requires
            `packageProxyPort` (the host proxy port guests are allowed to
            reach). Without it the profile would grant nothing beyond
            proxy-only.
          '';
        }
        {
          assertion = cfg.packageProxyPort == null || cfg.packageProxyPort != cfg.litellmPort;
          message = "myconfig.ai.microvm.packageProxyPort must differ from litellmPort.";
        }
        {
          # The guest-side forwarder and the host-side socket both point the
          # model API at the loopback LiteLLM proxy on
          # 127.0.0.1:<litellmPort>, and every guest agent config assumes that
          # endpoint exists. A host that enables a litellm-capable profile
          # (`proxy-only` / `package-access` / `internet`) WITHOUT
          # `services.litellm.enable` produces a sandbox whose guest can reach
          # the bridge endpoint but finds nothing behind it — so every batch
          # job dies a few seconds in with no actionable message. Fail this at
          # EVAL instead, naming the missing backend. (`offline` needs no
          # backend: its guests get no litellm capability.)
          assertion = !agentNetwork.caps.litellm || (config.services.litellm.enable or false);
          message = ''
            myconfig.ai.microvm: the effective network profile
            `${effectiveProfile}` lets guests reach the model API, but
            `services.litellm.enable` is false (or the litellm module is not
            imported). The guest-side loopback forwarder hands connections to
            `127.0.0.1:${toString cfg.litellmPort}`, which only exists when the
            host LiteLLM proxy is enabled — without it every agent batch job
            dies within seconds. Either enable `services.litellm` on this host
            or switch the microVM profile to `offline`.
          '';
        }
        {
          assertion = lib.length (lib.unique slotIPs) == lib.length slotIPs;
          message = "myconfig.ai.microvm: generated slot IPv4 addresses are not unique.";
        }
        {
          assertion = lib.length (lib.unique slotMACs) == lib.length slotMACs;
          message = "myconfig.ai.microvm: generated slot MAC addresses are not unique.";
        }
        {
          assertion = lib.length (lib.unique slotCIDs) == lib.length slotCIDs;
          message = "myconfig.ai.microvm: generated slot VSOCK CIDs are not unique.";
        }
        {
          # 0 (hypervisor), 1 (loopback) and 2 (host) are reserved VSOCK CIDs;
          # 0xffffffff is VMADDR_CID_ANY.
          assertion = lib.all (c: c > 2 && c < 4294967295) slotCIDs;
          message = "myconfig.ai.microvm: generated slot VSOCK CIDs must avoid the reserved values 0/1/2 and VMADDR_CID_ANY.";
        }
        {
          assertion = agentRegistry.declaredNames != [ ];
          message = "myconfig.ai.microvm: the agent registry (agents.nix) must declare at least one agent.";
        }
        {
          # A typo in `enabledAgents` must fail loudly at EVAL instead of
          # silently producing a guest with fewer (or no) agents.
          assertion = agentRegistry.unknownEnabled == [ ];
          message = ''
            myconfig.ai.microvm.enabledAgents: unknown agent(s) ${lib.concatStringsSep ", " agentRegistry.unknownEnabled}.
            Declared agents are: ${lib.concatStringsSep ", " agentRegistry.declaredNames}.
          '';
        }
        {
          # An empty selection would build a guest that can run nothing at all.
          assertion = agentRegistry.names != [ ];
          message = ''
            myconfig.ai.microvm.enabledAgents selects no agent, so the guest
            would contain no agent runtime at all. Select at least one of:
            ${lib.concatStringsSep ", " agentRegistry.declaredNames}.
          '';
        }
        {
          # The BATCH machinery (host `submit` validation, guest controller and
          # worker dispatch) renders `case` PATTERNS from the batch-capable
          # subset; an empty subset renders an empty pattern, i.e. a
          # syntactically broken script. Every declared agent is batch-capable
          # today, so this can only trip on a selection made specifically to
          # exclude them — which the (still combined interactive+batch) guest
          # cannot serve. Splitting the two modes (lightweight plan phase 5) is
          # what will make an interactive-only selection meaningful.
          assertion = agentRegistry.batchNames != [ ];
          message = ''
            myconfig.ai.microvm.enabledAgents selects no agent that can run
            UNATTENDED (no `batchArgs` in ./agents.nix), but every guest also
            carries the batch job machinery. Include at least one batch-capable
            agent: ${lib.concatStringsSep ", " agentRegistry.declaredBatchNames}.
          '';
        }
      ]
      # One assertion per malformed registry entry (empty when well-formed).
      ++ map (msg: {
        assertion = false;
        message = msg;
      }) agentRegistry.errors;

      # --- deprecation warnings (ticket 3 C migration) -------------------
      # Emitted for any legacy boolean a host still DEFINES, even when it is
      # false, so the migration is visible before the options are dropped.
      warnings =
        lib.optional (definedLegacySlotOpts != [ ] && !classesExplicit) ''
          myconfig.ai.microvm: ${lib.concatStringsSep ", " definedLegacySlotOpts} ${
            if lib.length definedLegacySlotOpts == 1 then "is" else "are"
          } deprecated; use `myconfig.ai.microvm.resourceClasses` instead. The
          pool is currently a single `normal` class with ${toString cfg.slotCount} slot(s) (${toString cfg.defaultVcpu} vCPU, ${toString cfg.defaultMemoryMiB} MiB).
        ''
        ++ lib.optional (definedLegacyOpts != [ ]) ''
          myconfig.ai.microvm: the network booleans ${lib.concatStringsSep ", " definedLegacyOpts} are deprecated; use `myconfig.ai.microvm.networkProfile` instead
          (currently effective: "${effectiveProfile}").
        ''
        ++ lib.optional (legacyWantsInternet && !profileExplicit) ''
          myconfig.ai.microvm: translated the deprecated
          `allowPublicInternet = true` into `networkProfile = "internet"`.
          Set `networkProfile` explicitly and drop the boolean.
        '';
    })
  ];
}
