# Copyright 2025 Maximilian Huber <oss@maximilian-huber.de>
# SPDX-License-Identifier: MIT
#
# myconfig.ai.microvm — Cloud Hypervisor agent-sandbox tier.
#
# A second, stronger isolation tier for autonomous coding agents, alongside
# the existing QEMU/SLiRP `flake.sandboxed-pi.nix` tier. It runs each agent
# session inside a Cloud Hypervisor microVM (via the `microvm.nix` flake
# input) with its own kernel, a disposable root/home, a single writable
# virtiofs `/workspace` mount (a standalone git clone), a dedicated private
# bridge, and model-API access restricted to the host LiteLLM proxy through a
# bridge-only forwarding endpoint. Every agent process and guest workload is
# treated as potentially hostile; the secure default prioritises isolation
# over convenience.
#
# PHASE 0 — this file only *defines the option namespace, assertions and
# registration*. The feature is disabled by default and, while disabled,
# produces no config side effects: it does NOT import the microvm.nix host
# module, create the bridge/firewall rules, define VM slots, build the guest,
# or register Workmux agents. Those are implemented in later phases inside
# guest.nix / network.nix / launcher.nix / workmux.nix. See
# `docs/agent-microvm/microvm-sandbox-plan.md` (§1, §37) for the authoritative
# option/assertion requirements.
{
  config,
  lib,
  ...
}:
let
  cfg = config.myconfig.ai.microvm;

  # --- deterministic fixed slot pool (agent-0 .. agent-<slotCount-1>) -----
  # The slot table is generated by the shared helper in slots.nix — the same
  # helper guest.nix uses to actually build the VMs — so these uniqueness /
  # bound assertions (§37) always guard the exact table that builds the VMs.
  slotLib = import ./slots.nix { inherit lib; };
  slots = slotLib.mkSlots cfg.slotCount;
  slotIPs = map (s: s.ip) slots;
  slotMACs = map (s: s.mac) slots;

  isAbsolutePath = p: lib.hasPrefix "/" p;
in
{
  imports = [
    ./guest.nix
    ./network.nix
    ./launcher.nix
    ./workmux.nix
  ];

  options.myconfig.ai.microvm = with lib; {
    enable = mkEnableOption "myconfig.ai.microvm (Cloud Hypervisor agent sandboxes)";

    slotCount = mkOption {
      type = types.ints.positive;
      default = 4;
      description = ''
        Number of fixed, declaratively defined microVM slots
        (agent-0 .. agent-<slotCount-1>). Bounds the maximum concurrent
        agent sandboxes. Must be positive.
      '';
    };

    defaultVcpu = mkOption {
      type = types.ints.positive;
      default = 4;
      description = "Default number of vCPUs per agent microVM.";
    };

    defaultMemoryMiB = mkOption {
      type = types.ints.positive;
      default = 8192;
      description = "Default guest RAM per agent microVM, in MiB.";
    };

    bridgeName = mkOption {
      type = types.str;
      default = "agentbr0";
      description = "Name of the dedicated private bridge for agent microVMs.";
    };

    subnet = mkOption {
      type = types.str;
      default = "192.168.83.0/24";
      description = "IPv4 subnet (CIDR) of the private agent bridge.";
    };

    gatewayAddress = mkOption {
      type = types.str;
      default = "192.168.83.1";
      description = ''
        Host-side IPv4 address on the agent bridge. Also the address on
        which the bridge-only LiteLLM forwarding endpoint listens.
      '';
    };

    litellmPort = mkOption {
      type = types.port;
      default = 4000;
      description = ''
        TCP port of the host LiteLLM proxy. The guest reaches the model API
        only via <gatewayAddress>:<litellmPort>, forwarded to the
        loopback-only LiteLLM proxy on 127.0.0.1:<litellmPort>.
      '';
    };

    workspaceRoot = mkOption {
      type = types.str;
      default = "/var/lib/agent-microvms/workspaces";
      description = ''
        Absolute host path under which per-task standalone git clones are
        created. Exactly one clone is mounted read-write into a slot at
        /workspace.
      '';
    };

    runtimeRoot = mkOption {
      type = types.str;
      default = "/var/lib/agent-microvms";
      description = ''
        Absolute host path for agent-microvm runtime state (task metadata,
        locks, bind-mount sources). Must be an absolute path.
      '';
    };

    stateRoot = mkOption {
      type = types.str;
      default = "/var/lib/microvms";
      description = ''
        Absolute host path used by microvm.nix for per-VM state
        (/var/lib/microvms/<slot>).
      '';
    };

    allowPublicInternet = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Allow agent guests to reach the public internet. INSECURE — must
        remain false for the secure default. Enabling it requires
        `acknowledgeInsecureNetwork = true`.
      '';
    };

    allowInterVmTraffic = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Allow traffic between agent microVMs (guest-to-guest / TAP-to-TAP).
        INSECURE — must remain false for the secure default. Enabling it
        requires `acknowledgeInsecureNetwork = true`.
      '';
    };

    allowPrivateNetworks = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Allow agent guests to reach private IPv4 ranges (host LAN, VPN
        peers, RFC1918, link-local, cloud metadata, ...). INSECURE — must
        remain false for the secure default. Enabling it requires
        `acknowledgeInsecureNetwork = true`.
      '';
    };

    acknowledgeInsecureNetwork = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Explicit opt-in acknowledging that one of the insecure network
        relaxations (allowPublicInternet / allowInterVmTraffic /
        allowPrivateNetworks) has been deliberately enabled. Without this,
        those flags must stay false (§37: "private-network / inter-VM /
        public internet without override").
      '';
    };

    enableSsh = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Expose an SSH server inside the guest, reachable only on the private
        guest interface. Requires `sshPublicKeyFile` to be set.
      '';
    };

    sshPublicKeyFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = ''
        Path to a single dedicated public key authorised for the guest
        `agent` user. Must NOT be a host authorized_keys file. Required when
        `enableSsh` is true.
      '';
    };
  };

  # Phase 0: the only config the module produces is its assertions, and even
  # those apply only when the feature is enabled — so importing the module
  # with the secure defaults (disabled) has no config side effects and never
  # blocks evaluation. Later phases add the microvm.nix host module, bridge,
  # firewall, slot definitions and Workmux registrations under this same
  # `lib.mkIf cfg.enable`.
  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.slotCount > 0;
        message = "myconfig.ai.microvm.slotCount must be > 0.";
      }
      {
        assertion = cfg.slotCount <= slotLib.maxSlotCount;
        message = "myconfig.ai.microvm.slotCount must be <= ${toString slotLib.maxSlotCount} (deterministic MAC/IPv4 generator bound).";
      }
      {
        assertion = cfg.defaultVcpu > 0;
        message = "myconfig.ai.microvm.defaultVcpu must be positive.";
      }
      {
        assertion = cfg.defaultMemoryMiB > 0;
        message = "myconfig.ai.microvm.defaultMemoryMiB must be positive.";
      }
      {
        assertion = isAbsolutePath cfg.workspaceRoot;
        message = "myconfig.ai.microvm.workspaceRoot must be an absolute path.";
      }
      {
        assertion = isAbsolutePath cfg.runtimeRoot;
        message = "myconfig.ai.microvm.runtimeRoot must be an absolute path.";
      }
      {
        assertion = isAbsolutePath cfg.stateRoot;
        message = "myconfig.ai.microvm.stateRoot must be an absolute path.";
      }
      {
        assertion = cfg.bridgeName != "";
        message = "myconfig.ai.microvm.bridgeName must be non-empty.";
      }
      {
        assertion = cfg.gatewayAddress != "";
        message = "myconfig.ai.microvm.gatewayAddress must be non-empty.";
      }
      {
        assertion = !cfg.enableSsh || cfg.sshPublicKeyFile != null;
        message = "myconfig.ai.microvm.enableSsh requires an explicit sshPublicKeyFile.";
      }
      {
        assertion =
          !(cfg.allowPublicInternet || cfg.allowInterVmTraffic || cfg.allowPrivateNetworks)
          || cfg.acknowledgeInsecureNetwork;
        message = ''
          myconfig.ai.microvm: allowPublicInternet / allowInterVmTraffic /
          allowPrivateNetworks must remain false for the secure default.
          To deliberately relax one of them, also set
          `myconfig.ai.microvm.acknowledgeInsecureNetwork = true`.
        '';
      }
      {
        assertion = lib.length (lib.unique slotIPs) == lib.length slotIPs;
        message = "myconfig.ai.microvm: generated slot IPv4 addresses are not unique.";
      }
      {
        assertion = lib.length (lib.unique slotMACs) == lib.length slotMACs;
        message = "myconfig.ai.microvm: generated slot MAC addresses are not unique.";
      }
    ];
  };
}
