# Copyright 2026 Maximilian Huber <oss@maximilian-huber.de>
# SPDX-License-Identifier: MIT
#
# Pure helpers for the per-device llama-server router backend.
#
# - `translateParamsToIni`: translate a model's free-form CLI `params`
#   list (e.g. `[ "--cache-type-k" "q8_0" ]`) into an attrset of INI
#   key/value pairs plus a list of `unhandled` shapes that the caller
#   can emit as INI comments for visibility.
# - `renderIni`: render a `[*]` global section + one section per model
#   into a `pkgs.writeText` derivation. Keys are emitted in sorted order
#   for reproducibility.
# - `mkRouterScript`: build the per-device `llama-server_<Device>` shell
#   wrapper that launches `llama-server --models-preset <ini>
#   --models-max <N> --port <port>`.
#
# Has no dependencies on NixOS modules — consumed by ../router.nix.
{
  lib,
  pkgs,
  devices,
}:
let
  inherit (devices) llamaServerFor envForDevice;

  # Translate a list of free-form `--flag value` / `-flag value` /
  # `--no-flag` CLI args into an attrset suitable for INI emission.
  #
  # Returns `{ keys = <attrset>; unhandled = <list of repr strings>; }`.
  #
  # Handled shapes:
  #   `[ "--foo" "bar" ]`        -> { foo = "bar"; }
  #   `[ "-c" "8192" ]`          -> { c = "8192"; }       # short forms (README-supported)
  #   `[ "--no-mmproj" ]`        -> { no-mmproj = true; } # lone flag (no value)
  #   `[ "--mmproj" "/path" ]`   -> { mmproj = "/path"; }
  #
  # Anything that doesn't fit (bare positional values, multi-value
  # flags, repeated flags, etc.) goes into `unhandled` so the caller
  # can surface it as an `; UNHANDLED: …` comment in the generated INI.
  translateParamsToIni =
    params:
    let
      # Strip leading dashes. "--foo" -> "foo", "-c" -> "c".
      stripDashes =
        s:
        let
          m = builtins.match "-+([^=].*)" s;
        in
        if m != null then builtins.head m else null;

      isFlag = s: stripDashes s != null;

      # Walk the params list left-to-right.
      go =
        acc: rest:
        if rest == [ ] then
          acc
        else
          let
            head = builtins.head rest;
            tail = builtins.tail rest;
            key = stripDashes head;
          in
          if key == null then
            # Bare value with no preceding flag — surface it.
            go (
              acc
              // {
                unhandled = acc.unhandled ++ [ "bare value: ${head}" ];
              }
            ) tail
          else if tail == [ ] || isFlag (builtins.head tail) then
            # Lone flag (no value follows).
            go (
              acc
              // {
                keys = acc.keys // {
                  ${key} = true;
                };
              }
            ) tail
          else
            # Flag + value.
            let
              value = builtins.head tail;
              rest' = builtins.tail tail;
              existing = acc.keys.${key} or null;
            in
            if existing != null then
              # Same key set twice — INI can't express that; preserve
              # the first occurrence and surface the duplicate.
              go (
                acc
                // {
                  unhandled = acc.unhandled ++ [
                    "duplicate flag: --${key} ${value} (already set to ${toString existing})"
                  ];
                }
              ) rest'
            else
              go (
                acc
                // {
                  keys = acc.keys // {
                    ${key} = value;
                  };
                }
              ) rest';
    in
    go {
      keys = { };
      unhandled = [ ];
    } params;

  # Render a single `key = value` line. Booleans become true/false;
  # everything else is stringified verbatim.
  renderKeyValue =
    key: value:
    let
      rendered =
        if value == true then
          "true"
        else if value == false then
          "false"
        else if builtins.isInt value then
          toString value
        else
          toString value;
    in
    "${key} = ${rendered}";

  # Render an attrset of key/value pairs into a list of lines, keys
  # sorted alphabetically so insertion order doesn't affect the hash.
  renderKeys = attrs: map (k: renderKeyValue k attrs.${k}) (lib.attrNames attrs);

  # Render a single section: `[name]` header + keys + unhandled comments.
  renderSection =
    {
      name,
      keys,
      unhandled ? [ ],
    }:
    [
      ""
      "[${name}]"
    ]
    ++ renderKeys keys
    ++ map (u: "; UNHANDLED: ${u}") unhandled;

  # Render a complete INI file. Returns a derivation produced by
  # `pkgs.writeText`.
  renderIni =
    {
      name,
      globals,
      sections,
    }:
    let
      header = [
        "; Generated by myconfig.ai.llama-cpp router backend"
        "version = 1"
        ""
        "[*]"
      ];
      globalLines = renderKeys globals;
      sectionLines = lib.concatMap renderSection sections;
      text = lib.concatStringsSep "\n" (header ++ globalLines ++ sectionLines) + "\n";
    in
    pkgs.writeText name text;

  # Stringify a key/value as it should appear in the INI file. The
  # `services.llama-cpp.modelsPreset` option from nixpkgs is typed as
  # `attrsOf attrs` and is fed through `lib.generators.toINI {}`, which
  # accepts bool/int/string directly — but to keep the on-wire INI
  # byte-identical to the wrappers' INI we coerce booleans to
  # "true"/"false" strings and ints to their decimal form here too.
  stringifyValue =
    value:
    if value == true then
      "true"
    else if value == false then
      "false"
    else if builtins.isInt value then
      toString value
    else
      toString value;

  stringifyKeys = attrs: lib.mapAttrs (_: stringifyValue) attrs;

  # Convert the `{ globals, sections }` shape into the attrset shape
  # required by `services.llama-cpp.modelsPreset` (which is fed to
  # `lib.generators.toINI`). The `[*]` global section becomes the "*"
  # key; each model becomes a key under its `name`. `unhandled`
  # comments are dropped here because nixpkgs' toINI has no concept of
  # comments — the home-manager wrappers' INI still surfaces them.
  toModelsPreset =
    {
      globals,
      sections,
    }:
    {
      "*" = stringifyKeys globals;
    }
    // lib.listToAttrs (
      map (s: {
        name = s.name;
        value = stringifyKeys s.keys;
      }) sections
    );

  # Build the per-device wrapper. Usage: `llama-server_<Device> [port] [extra args]`.
  mkRouterScript =
    {
      device,
      port,
      iniFile,
      modelsMax,
    }:
    let
      server = llamaServerFor device;
      scriptName = "llama-server_${device}";
      envExports = lib.concatStringsSep "\n" (map (e: "export ${e}") (envForDevice device));
    in
    pkgs.writeShellApplication {
      name = scriptName;
      runtimeInputs = [ ];
      text = ''
        ${envExports}
        exec ${server} \
          --host 127.0.0.1 \
          --port "''${1:-${toString port}}" \
          --models-preset ${iniFile} \
          --models-max ${toString modelsMax} \
          "''${@:2}"
      '';
    };
in
{
  inherit
    translateParamsToIni
    renderIni
    toModelsPreset
    mkRouterScript
    ;
}
