name: CI

on: [push]


jobs:
  build-os:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { hostname: x1extremeG2 , mode: "--dry-run" }
          # - { hostname: x1extremeG2 , mode: "" }
          - { hostname: vserver , mode: "--dry-run" }
          - { hostname: vserver , mode: "" }
          - { hostname: workstation , mode: "--dry-run" }
          - { hostname: workstation , mode: "" }
          - { hostname: nas , mode: "--dry-run" }
          - { hostname: nas , mode: "" }
      fail-fast: false

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: maxhbr
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: ./scripts/test-nixos-configuration.sh ${{ matrix.config.mode }} --hostname ${{ matrix.config.hostname }}

  build-iso:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { config: "" , secondaryConfig: "" , mode: "--dry-run" }
          # - { config: "role.headless" , secondaryConfig: "" , mode: "--dry-run" }
          # - { config: "role.dev" , secondaryConfig: "host.vserver" , mode: "--dry-run" }
          # - { config: "" , secondaryConfig: "" , mode: "--push-to-cachix" } # runs out of disk space
      fail-fast: false

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: maxhbr
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: ./scripts/build-iso-image.sh ${{ matrix.config.mode }} ${{ matrix.config.config }} ${{ matrix.config.secondaryConfig }}

