name: CI

on: [push]


jobs:
  build-dry:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { hostname: core }
          - { hostname: base }
          - { hostname: dev }
          - { hostname: x1extremeG2 }
          - { hostname: headless }
          - { hostname: vserver }
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - run: ./test-nixos-configuration.sh --dry-run --hostname ${{ matrix.config.hostname }}

  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       config:
  #         - { hostname: core }
  #         # - { hostname: base }
  #         # - { hostname: dev }
  #         - { hostname: vserver }
  #     fail-fast: false
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Install Nix
  #     uses: cachix/install-nix-action@v6
  #   - run: ./test-nixos-configuration.sh --hostname ${{ matrix.config.hostname }}

  # build-iso:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       config:
  #         - { hostname: core }
  #     fail-fast: false
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Install Nix
  #     uses: cachix/install-nix-action@v6
  #   - run: ./iso-rebuild.sh ${{ matrix.config.hostname }}


