name: CI

on: [push]


jobs:
  build-os:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { hostname: core , mode: "--dry-run" }
          - { hostname: core , mode: "--push-to-cachix" }
          - { hostname: headless , mode: "--dry-run" }
          - { hostname: headless , mode: "--push-to-cachix" }
          - { hostname: dev , mode: "--dry-run" }
          - { hostname: dev , mode: "--push-to-cachix" }
          - { hostname: desktop , mode: "--dry-run" }
          - { hostname: x1extremeG2 , mode: "--dry-run" }
          - { hostname: vserver , mode: "--dry-run" }
          - { hostname: workstation , mode: "--dry-run" }
          - { hostname: nas , mode: "--dry-run" }
      fail-fast: false

    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: maxhbr
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: ./scripts/test-nixos-configuration.sh ${{ matrix.config.mode }} --hostname ${{ matrix.config.hostname }}

  build-iso:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { config: "" , secondaryConfig: "" , mode: "--dry-run" }
          - { config: "role.headless" , secondaryConfig: "" , mode: "--dry-run" }
          - { config: "role.dev" , secondaryConfig: "role.headless" , mode: "--dry-run" }
          - { config: "" , secondaryConfig: "" , mode: "--push-to-cachix" }
      fail-fast: false

    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: maxhbr
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: ./scripts/build-iso-image.sh --dry-run


  # build-iso:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       config:
  #         - { hostname: core }
  #     fail-fast: false
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Install Nix
  #     uses: cachix/install-nix-action@v6
  #   - run: ./iso-rebuild.sh ${{ matrix.config.hostname }}


