name: CI

on: [push]


jobs:
  build-dry:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { hostname: core , mode: "--dry-run" }
          - { hostname: core , mode: "" }
          - { hostname: dev , mode: "--dry-run" }
          - { hostname: desktop , mode: "--dry-run" }
          - { hostname: x1extremeG2 , mode: "--dry-run" }
          - { hostname: headless , mode: "--dry-run" }
          - { hostname: vserver , mode: "--dry-run" }
      fail-fast: false

    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: maxhbr
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: ./scripts/test-nixos-configuration.sh ${{ matrix.config.mode }} --hostname ${{ matrix.config.hostname }}

  # build-iso:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       config:
  #         - { hostname: core }
  #     fail-fast: false
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Install Nix
  #     uses: cachix/install-nix-action@v6
  #   - run: ./iso-rebuild.sh ${{ matrix.config.hostname }}


