name: CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { hostname: core }
          # - { hostname: base, allow_failure: true }
          - { hostname: vserver }
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - run: df -h
    - run: free
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - run: cd ./nixos && ./test-nixos-configuration.sh --ci --hostname ${{ matrix.config.hostname }}
      continue-on-error: ${{ matrix.config.allow_failure }}

  build-iso:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { hostname: core }
          # - { hostname: base, allow_failure: true }
          # - { hostname: vserver }
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - run: cd ./nixos && ./iso-rebuild.sh ${{ matrix.config.hostname }}
      continue-on-error: ${{ matrix.config.allow_failure }}


