name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/setup-nix
      - name: Check nix fmt
        run: |
          nix fmt
          git diff --exit-code
      - name: Run flake check
        run: nix flake check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/setup-nix
      - name: Run tests
        run: nix build .#checks.x86_64-linux.transform-packages --print-build-logs
